### ISSUE TITLE
React.renderToString() and Helmet.constructor.rewind() not working

### ISSUE THREAD

**Issue by choonkending** [nfl/react-helmet#1]
Thanks for the repo, it solves what I've been attempting to solve with `<link>` and `<meta>` tags. 

### Problem:
1. `React.renderToString(<Handler />); ` retuns a `noscript` tag
2. `Helmet.constructor.rewind()` throws a
```javascript
TypeError: Object function Function() { [native code] } has no method 'rewind'
```

### Config information

- npm version: 2.11.2
- node version: v0.10.33
- building tool: webpack with babel-loader, my exact config file is [here](https://github.com/choonkending/react-webpack-node/blob/feature/universal_js/webpack.config.js)

### What I have attempted

Running this
```javascript
import React from "react";
import Helmet from "react-helmet";

class Application extends React.Component {
    render() {
        return (
                <Helmet title="My Title"/>
        );
    }
};

let app = React.renderToString(<Application />);
console.log(app);
// returns <noscript data-reactid=".tqn1t74i68" data-react-checksum="-1541140300"></noscript>

```

I think it was because [this line](https://github.com/nfl/react-helmet/blob/master/src/Helmet.jsx#L162) was executed, i.e. it returned a `null` object.

I also tried running:
```
// throws TypeError: Object function Function() { [native code] } has no method 'rewind'
Helmet.constructor.rewind()
```

Then I tried:
```
let head = Helmet.rewind();
console.log(head);
// Output: { title: '', meta: '', link: '' }
```

### Reduced Test Case
 I don't have a reduced test case of this problem, but I'm attempting to use it [this](https://github.com/choonkending/react-webpack-node/blob/89e63bf1899d5f922c1cf913b0643587cec63c5e/app/elements/Header.react.js) way.

Do let me know if you require more information, or if I am taking the wrong approach. Thanks!

**Comment by snow01** [comment]
Fixed this issue here and submitted a pull request - https://github.com/nfl/react-helmet/pull/2

My branch till then - https://github.com/snow01/react-helmet.git

Thanks!

**Comment by choonkending** [comment]
Thanks @snow01! I gave it a shot and now running `Helmet.rewind()` gives me an object that I can use to render on the server side. Hopefully it gets merged!

I went through `Helmet.jsx` and have a couple of questions in general.

1. What is the reason/use case for having the [render()](https://github.com/nfl/react-helmet/blob/master/src/Helmet.jsx#L151) method only render `this.props.children`?
   ```javascript
       // render in Helmet.jsx 
       render() {
            if (Object.is(React.Children.count(this.props.children), 1)) {
                return React.Children.only(this.props.children);
            } else if (React.Children.count(this.props.children) > 1) {
                return (
                    <span>
                        {this.props.children}
                    </span>
                );
            }

            return null;
        }
    ```

  My initial expectation for the `render` method was:

    - if there is > 1 `prop`, render those props as elements (something) within a `span` or `head` element.

    ```javascript
    <Helmet
        link={[
            {"rel": "apple-touch-icon", "href": "http://mysite.com/img/apple-touch-icon-57x57.png"},
            {"rel": "apple-touch-icon", "sizes": "72x72", "href": "http://mysite.com/img/apple-touch-icon-72x72.png"}
        ]}
    />

    /* 
     * Expected renderToString() behavior
     */
    <head>
        <link rel="apple-touch-icon" href="http://mysite.com/img/apple-touch-icon-57x57.png" />
        <link rel="apple-touch-icon" sizes="72x72" href="http://mysite.com/img/apple-touch-icon-72x72.png" />
    </head>

    /* 
     * Actual renderToString() behavior
     */
    <noscript data-reactid=".tqn1t74i68" data-react-checksum="-1541140300"></noscript>
    ```
    - The current behaviour of `render()` (Correct me if I'm wrong) :
    ```javascript
    class Header extends React.Component {
      render() {
        return (
          <Helmet>
            <link rel="stylesheet" href="yoyo" />
            <link rel="stylesheet" href="yaya" />
          </Helmet>
        );
      }
    }

    let header = React.renderToString(<Header />);
    /*
     * header evaluates to
     */
    <span data-reactid=".jris83nif4" data-react-checksum="524499219">
       <link rel="stylesheet" href="yoyo" data-reactid=".jris83nif4.0">
       <link rel="stylesheet" href="yaya" data-reactid=".jris83nif4.1">
    </span>
    ```

    In the examples section, it was not immediately apparent why we should use `rewind()` instead of using `React.renderToString()`. That was my source of confusion. Perhaps provide more examples for server side usage?

2. Why does the [server usage](https://github.com/nfl/react-helmet#server-usage) example use `Helmet.constructor.rewind()`?

[The code here](https://github.com/nfl/react-helmet/blob/master/src/Helmet.jsx#L141) shows that it's a static method. :)

**Comment by snow01** [comment]
Above questions show a very fundamental confusion about working of react-helmet. Let me try explain here --

1. link, meta all reside in head section of the HTML page, while displayable content resides in body section of the page.

2. We do not want to (or probably we can not) control head section of the page through react.

3. And in a single page application - we have only single opportunity to generate head section -- the time when we load the page from server.

4. But even in single page application we want to have a different title, meta tags (specially for integration with FB, Twitter etc). Say you have products on your site - for each product page you would want to have different title. Doing this in single page app is tough.

5. But in a fully structured system, we may not have a single place where we can define all meta information. In some cases, title may be coming from component A (say VideoCard component), in another case from component B (say ArticleCard component). That is decision for what meta tags should be there in page is not at single place, but it is distributed into multiple components.

_What is the reason/use case for having the render() method only render this.props.children?_
_if there is > 1 prop, render those props as elements (something) within a span or head element._

6. You can assume react-helmet as a collector of properties. Through <Helmet meta={}/> you do not intend to render anything - but want to collect all the meta properties seen in the entire render cycle. You define meta tags at the most appropriate component, wherever data is available. There can be multiple components defining <Helmet .../> - at the end of the render cycle, Helmet component collects all property types and attaches them into head section. That's the exact purpose of react-helmet - to be able to generate meta tags.

_Why does the server usage example use Helmet.constructor.rewind()?_

7. For isomorphic applications, when you generate page at server side - React provides you only one way to get the output - as string. But during that renderToString process a side effect has run - side-effect of collecting all meta tags. You access all meta tags object through rewind() - rewind() is used for two purposes: (a) to give you all properties collected, which you can write into a page through jade or something (b) cleanup all the memory it would have created to collect these meta tags.

**Comment by KATT** [comment]
This is what I just made up to solve the server-side problem in my [fluxible](fluxible.io) app

```js
debug('Rendering Application component into html');
let html = React.renderToStaticMarkup(htmlComponent({
    context: context.getComponentContext(),
    state  : exposed,
    markup : React.renderToString(context.createElement())
}));
// Get head tags from Helmet
let headMap = Helmet.rewind();

// Make sure they are all HTML
headMap.title = `<title>${headMap.title}</title>`;

// Get all dem HTML tags
let headHtml = Object.values(headMap).join('\n');

debug(`<head> inject from Helmet:\n${headHtml}`);
headHtml = headHtml.replace(/(\r\n|\n|\r)/gm, '');

// inject them in the HTML
html = html.replace('</head>', `${headHtml}</head>`);



debug('Sending markup');
res.type('html');
res.write('<!DOCTYPE html>' + html);
res.end();
```

**Comment by choonkending** [comment]
@snow01 
Thanks for clearing that up.

*link, meta all reside in head section of the HTML page, while displayable content resides in body section of the page.*

Haha thanks I know this part.

*You can assume react-helmet as a collector of properties. Through you do not intend to render anything - but want to collect all the meta properties seen in the entire render cycle. You define meta tags at the most appropriate component, wherever data is available. There can be multiple components defining - at the end of the render cycle, Helmet component collects all property types and attaches them into head section. That's the exact purpose of react-helmet - to be able to generate meta tags.*

This was a very good explanation. 

@KATT

I had a similar idea for my isomorphic [alt app](https://github.com/choonkending/react-webpack-node). I've been using webpack's html-loader for rendering the html on a branch currently and been experimenting with react-helmet.

The idea is to render the main app and the head section with webpack as 2 separate entry points (from the server), and replacing the content on a response much like yours. Thanks.
