### ISSUE TITLE
aggregate script tags

### ISSUE THREAD

**Issue by benmonro** [nfl/react-helmet#105]
Currently, it appears that if a parent component/page uses helmet with script tags, and a child component also uses script tags, the child script tags will replace the parent script tags.  I would like the ability for these scripts to be aggregated such that parent scripts would be combined or aggregated with the child scripts so that all the necessary scripts are properly loaded into the head.

**Comment by cwelch5** [comment]
Helmet will include both scripts in the head if the parent and child scripts have different `src` values.  Can you name the child scripts differently in order to preserve both sets of scripts?

**Comment by cwelch5** [comment]
@benmonro Post another issue if you still have a need for aggregating the scripts, although I think you can name the scripts differently to preserve both scripts appearing in your document head.  Closing for now.
