### ISSUE TITLE
Webpack and CommonsChunksPlugin

### ISSUE THREAD

**Issue by dbismut** [nfl/react-helmet#107]
My app has SSR and separate chunks that I load via require.ensure and CommonsChunkPlugin from webpack. 

This is what my chunks look like:

```javascript
{ 
   publicPath: '/assets/',
   assetsByChunkName: {
      main: [ 'web.js', 'style.css', 'web.js.map', 'style.css.map' ],
      producer: [ '1.web.js', '1.web.js.map' ],
      common: [ 'common.web.js', 'common.web.js.map' ]
   }
}
```

When I use `react-helmet`, I'm running into as I load the producer chunk. 

```
common.web.js:1 Uncaught TypeError: Cannot read property 'call' of undefined)...
```

I really don't know what's happening here, maybe someone can help. Many thanks.

**Comment by cwelch5** [comment]
I'm not sure if this would be affected by Helmet.  But if you remove Helmet, everything works fine?  And are you removing the "react-helmet" import, or removing the Helmet component from your component?

**Comment by dbismut** [comment]
Hi @cwelch5, thanks for your interest! I was removing both the Helmet and the import. But yes, it's the very only thing that I'm changing...

I just tried having `react-helmet` in only the main chunk only, and keeping the import in the producer chunk, and I'm getting the same error...

**Comment by dbismut** [comment]
It seems related to the Dedupe plugin from webpack. Disabling the plugin makes it work.

**Comment by cwelch5** [comment]
Thx @dbismut I'll try to reproduce on my end and figure out what causes this.
