### ISSUE TITLE
Recalculate title on routing

### ISSUE THREAD

**Issue by indeyets** [nfl/react-helmet#109]
I use react-router and have the following structure:

```
<Route component={App}>
  <Route component={Component1} path="/" />
  <Route component={Component2} path="/path2" />
</Route>
```

* `App` has `<Helmet title="" titleTemplate="%sTestSite />`
* `Component 1` has `<Helmet title="Component1 of "/>`
* `Component 2` doesnt' have Helmet-tag

The issue is, that if I navigate from Component1 to Component2 (client-side) title is not reset to the default, but still shows `Component1 of TestSite`.

I do plan to set titles in all relevant components, but lack of reset complicates development

**Comment by LouisTakePILLz** [comment]
It would be nice to see this fixed.

**Comment by cwelch5** [comment]
Currently, the `Component1 of TestSite` remains, even when navigating to Component 2 because `App` has a blank title and Helmet won't update you to a blank title if you already had a non-blank one:

```
const updateTitle = title => {
    document.title = title || document.title;
};
```

Also, `titleTemplate` only has effect when there is a non-blank title.

What behavior would you like to see instead?

**Comment by indeyets** [comment]
well, setting blank title is one option. Might be the best option, actually. Why do you think it's bad? 

Another option is to throw exception on blank title, but I'm not sure that's a good thing to have in production. But it could have some in dev-mode

**Comment by cwelch5** [comment]
Helmet will not give you a blank title if you've already been to a route with a real title.  This is to make sure you didn't make a mistake.  Could you give a valid title at the `App` level?  If you did that, you would see the title change.  And then when you are done validating Component 2, you'll never see `App`'s title again.

**Comment by indeyets** [comment]
well, in my example empty title is not an error. I modeled titleTemplate in a way, which accommodates to it. In the end we have similar reasoning, but different approaches. I want to control the default title, while still being able to use title-templates.

would differentiation between empty string and undefined work for your usage? I can send a patch :)

```
if (title !== undefined) {
  document.title = title;
}
```

**Comment by doctyper** [comment]
Would this address your issue @ineyets? `<Helmet title="TestSite" titleTemplate="%sTestSite />`

**Comment by indeyets** [comment]
@doctyper nope. that would give me `<title>TestSiteTestSite</title>` for unhandled pages

**Comment by jmurzy** [comment]
@indeyets I created a PR that should address this. See #117.

Let me know what you guys think.
