### ISSUE TITLE
html tag - lang and amp support

### ISSUE THREAD

**Issue by cwelch5** [nfl/react-helmet#110]
Looking to extend Helmet to support new attributes to add to the html tag.  Most likely avoid validating html tag as their may be cases where it's just `<html>`, and that should obviously be a valid case.

**Comment by cwelch5** [comment]
API suggestions:

On Server:
```
const head = Helmet.rewind();
<html {head.htmlAttributes.toString()}
     ...
</html>
```

In Component:
```
<Helmet
     htmlAttributes={[{"lang", "en"}]}
/>
```

**Comment by clayne11** [comment]
I think your example for the component is not formed correctly. How do you know which is the key and which is the value? You seem to have a dictionary with only keys. I think it should be:
```
<Helmet
     htmlAttributes={{"lang": "en"}}
/>
```

**Comment by cwelch5** [comment]
The only difference between our versions is mine is an array.  And that is because I plan to add other htmlAttributes, specifically amp.  Just deciding the best api for the amp configuration.

**Comment by clayne11** [comment]
Yours isn't just an array. Your array has a malformed object inside of it. Was your goal to make it like this:

```
<Helmet
     htmlAttributes={[["lang", "en"], ["amp", "test"]]}
/>
```

?

**Comment by cwelch5** [comment]
I'm modeling this new API based on our current API, it's array of objects.  So in your example, it would look like this:

```
<Helmet
     htmlAttributes={[
          {"lang": "en"},
          {"amp": "test"}
     ]}
/>
```

If I did just the lang:
```
<Helmet
     htmlAttributes={[
          {"lang": "en"}
     ]}
/>
```

The output in the DOM would be:
```
<html lang="en">
```

**Comment by clayne11** [comment]
I agree with your latest comment. Your original comment had a malformed JSON object if you go back and look at it:

```
<Helmet
    htmlAttributes={[
        {"lang", "en"}
    ]}
/>
```

So you intended for the comma to be a colon, and that proposed API looks good to me.

**Comment by cwelch5** [comment]
@clayne11 Thx, it was a typo on my end.  Sorry for the confusion.

**Comment by juliagarant** [comment]
When using this in component form 
`<Helmet 
htmlAttributes={[
{"lang": "en"}
]}
/>`

do you need to include anything else? I can't find any other way to create the equivalent tag to `<html lang="en">` in react.
