### ISSUE TITLE
Conflict with core-js

### ISSUE THREAD

**Issue by SkateFreak** [nfl/react-helmet#111]
anonymous/node_modules/react-helmet/node_modules/core-js/modules/_hide.js:4
    return $.setDesc(object, key, createDesc(1, value));
              ^

        TypeError: Cannot redefine property: Symbol(Symbol.iterator)

core-js is a ```Mongoosastic``` dependency if i get it right.
any idea?

**Comment by cwelch5** [comment]
We are in the process of deprecating, then removing polyfills from Helmet.

**Comment by SkateFreak** [comment]
@cwelch5 i found out that importing Helmet before Mongoosastic (which uses.l core.js for my understanding) solves the issue for now

**Comment by doctyper** [comment]
Fixed in [`react-helmet@3.0.0`](https://www.npmjs.com/package/react-helmet)
