### ISSUE TITLE
Remove core-js polyfills 

### ISSUE THREAD

**Issue by chrisbateman** [nfl/react-helmet#112]
Automatically including polyfills can lead to a number of issues:

- An application may already be polyfilling some features - leading to duplication/bloat.
- An application may only be supporing browsers which support a particular feature, making the polyfill unnecessary weight.
- An application may inadvertently rely on polyfill brought in by a library - and then be confused about why the feature no longer works after removing the library.

Another alternative might be to provide both a build with the polyfills and a build without them (which would require the application to provide and manage the polyfills).

Thanks!

**Comment by olegpesok** [comment]
I haven't investigated enough, but I am seeing the polyfills cause problems with a project we have using ImmutableJS on some browsers including IE11. I would say this is even more serious than the original suggestion.

**Comment by cwelch5** [comment]
We are in the process of deprecating, then removing polyfills from Helmet.  Should address this and #111

**Comment by doctyper** [comment]
Fixed in [`react-helmet@3.0.0`](https://www.npmjs.com/package/react-helmet)

**Comment by chrisbateman** [comment]
Thanks very much, this is great!
