### ISSUE TITLE
Support itemprop

### ISSUE THREAD

**Issue by clayne11** [nfl/react-helmet#113]
Rich snippets use `itemprop` tags. To take full advantage of rich snippet schemas you also need to update the `html` tag of the document with to point to the schema.

Can we add support for this use case? It's important for SEO.

**Comment by cwelch5** [comment]
We can consider this.  We are starting to add html attributes with #110

**Comment by gerardmrk** [comment]
+ 1 I am using react-helmet in an app right now being pushed to production soon, and would really like to have itemprop for SEO reasons

**Comment by cwelch5** [comment]
With the lastest Helmet release (3.0.0 just released) you can now use [JSON-LD](https://developers.google.com/schemas/formats/json-ld?hl=en).  @gerardmrk will that fit your needs in the interim?

@clayne11 Will JSON-LD support suffice, or do you still require `itemprop` support?  And if you still need it, what would that fully entail (I could use an example or two, thank you)?

**Comment by dattran92** [comment]
About the 'itemprop' attribute in title tag: 
[http://inchoo.net/online-marketing/in-mobile-serp-title-tags-no-longer-control-whats-shown/](http://inchoo.net/online-marketing/in-mobile-serp-title-tags-no-longer-control-whats-shown/)

It's a requirement of my company's SEO specialist. So I think others may also need it.

**Comment by cwelch5** [comment]
@dattran92 - In that link you sent it mentions JSON-LD as another option for title.  So, maybe spend your effort on meta only.  Unless that won't work for your title case for some reason.

**Comment by dattran92** [comment]
@cwelch5 - That's the requirement from my company's SEO specialist. So I have to implement it and I think that others may also need it. 
I'm not sure about JSON-LD. So why don't we just give people the two options? (JSON-LD or just put more attributes to meta and title tag).
I don't know if you want it in your project. Therefore, I ask first before sending you a pull request. So just let me know if you're OK with it.

**Comment by cwelch5** [comment]
@dattran92 - Thanks for asking, yes, we would like as robust an API as possible.  So if there is a spec and a need for it, we'd like to include it.  We welcome a PR.  Thanks.

**Comment by dryhopped** [comment]
Is this feature still something that is being considered? If so, I would like to work on implementing it. I have been using this library in my latest project and am in need of the itemProp support for meta tags as well. I don't have need of the title tag supporting it, but would be happy to implement that as well if there's a need for it.

**Comment by dattran92** [comment]
Implemented already but no one accept my merge request.
[https://github.com/dattran92/react-helmet](https://github.com/dattran92/react-helmet)

**Comment by clayne11** [comment]
You need to agree to the contributor's license.

https://github.com/nfl/react-helmet/pull/169

**Comment by dattran92** [comment]
I have agreed already but don't know why it didn't update in the pull request.

**Comment by doctyper** [comment]
Looks like you used a different email address to commit. Can you address that?

> Dat Tran seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.

**Comment by roastlechon** [comment]
@dattran92 We just came across this at work and seem to be blocked by this. Any chance that you can push this through?
