### ISSUE TITLE
Unexpected : htmlAttribute remove existing attribute on html tag

### ISSUE THREAD

**Issue by singggum3b** [nfl/react-helmet#121]
As title said, new htmlAttribute feature cause existing attr on html tag to be erased. (eg class..)

**Comment by alampros** [comment]
In case anyone else has the same problem, this is why modernizr feature detect classes weren't showing up on the `<html>` node.

**Comment by cusxio** [comment]
Seems like this issue is fix. How long does it take to publish it to NPM ?

**Comment by dhoward** [comment]
As of release 3.0.1 this issue is now fixed

**Comment by cusxio** [comment]
Indeed. Can confirm that release 3.0.1 fixes issue with Modernizr.

**Comment by manneredboor** [comment]
Looks like the problem has appeared again
