### ISSUE TITLE
The <Helmet /> renders as <noscript> tags

### ISSUE THREAD

**Issue by bguiz** [nfl/react-helmet#124]
When rendering on the server, both on the client and the server, wherever the `<Helmet>` tag is the JSX component, the rendered output for it is `<noscript></noscript>`.

React renders `<noscript>` for components that return null when rendering... so what could cause the `Helmet` to render null?

I'm using `react-router@2.0.1` and `react@0.14.8`

**Comment by cwelch5** [comment]
Helmet renders null because the rendering is inconsequential toward the main purpose of Helmet.  You know Helmet worked because of how it changed your <head>.  I suppose we would accept a PR to have Helmet render empty string.  What do other folks think?

**Comment by bausmeier** [comment]
From v15 React will render comment nodes instead of `<noscript>` when returning null. See https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html#rendering-null-now-uses-comment-nodes.

**Comment by bguiz** [comment]
@cwelch The problem is that none of the components nested within `<Helmet>` and `</Helmet>` get rendered either. Just `<noscript></noscript>` and that is all. If I do not nest components within it, then it is fine - but the document title and other things do not appear properly. 

Is there an example app using `react-router@2` and `react@0.14` working with Helmet that I an use  as a reference?

**Comment by bguiz** [comment]
@bausmeier Thanks for the input, I'm not on `react@15` yet though!

**Comment by cwelch5** [comment]
@bguiz `Helmet` will not render children (as designed).  Title and other head attributes are all working correctly.  Please refer to the unit tests.  We have successfully tested `Helmet` with `react-router@2.2.4`.
