### ISSUE TITLE
Using `react-router@2.0.1`, `Helmet.rewind()` doesn't give the expected results

### ISSUE THREAD

**Issue by bguiz** [nfl/react-helmet#125]
In the following snippet, when rendering on the server:

    let rendered = ReactDomServer.renderToStaticMarkup(
            <RouterContext {...renderProps} />);
    let head = Helmet.rewind();
    const html = `
        <!doctype html>
        <html>
            <head ${head.htmlAttributes.toString()}>
                ${head.title.toString()}
                ${head.meta.toString()}
                ${head.link.toString()}
            </head>
            <body>
                <div id="content">
                    // React stuff here
                </div>
            </body>
        </html>
    `;

the value of `html` is:

      <!doctype html>
      <html>
          <head >
              
              
              
          </head>
          <body>
              <div id="content">
                  // React stuff here
              </div>
          </body>
      </html>

... so basically all the `toString()`s simply output empty strings.
The rest of the rendering is OK, with all my components rendering as they're
are expected to.

Is there anything wrong with my snippet above?

**Comment by madpilot** [comment]
I'm also seeing this bug. When the same code renders client side, it works fine.

**Comment by bguiz** [comment]
My guess is that it doesn't support the mew react-router yet

**Comment by doctyper** [comment]
@bguiz We use RR 2.0.1 + Helmet in-house and we haven't seen any conflicts between the libraries.

**Comment by yukulelix** [comment]
+1 I'm having the same issue here : Helmet.rewind is giving me empty fields on server while it's working good on client side !

**Comment by bguiz** [comment]
@doctyper It seems that several of us here are having issues. Just
confirming that you are using it for server rendering as well?

If so, could you please update the react-helmet-example to use
react-router@2 (it's currently using react-router@0.13):
https://github.com/mattdennewitz/react-helmet-example/blob/master/package.json#L12

... and then I'd like to see what is done differently when rendering
on the server: https://github.com/mattdennewitz/react-helmet-example/blob/master/server.js#L30-L48

CC @mattdennewitz
W: http://bguiz.com

**Comment by doctyper** [comment]
@bguiz Yes indeed, we are using React Router 2.0.1 + Helmet 3.0.1 in [production](https://www.nfl.com/super-bowl-city) with server-side-rendering.

There is a working example in our [Wildcat example project](https://github.com/nfl/react-wildcat/tree/master/example).

**Comment by yukulelix** [comment]
@doctyper That's strange ! My code is really simple :
```jsx
import routes from '../../assets/src/scripts/routes'
import { renderToString } from 'react-dom/server'
import Helmet from 'react-helmet'
import { match, RouterContext } from 'react-router'
import express from 'express';

export const app = express();
app.get('*',(req, res) => {
    match({ routes, location: req.url }, (error, redirectLocation, renderProps) => {
            let content = renderToString(<RouterContext {...renderProps} />);
            let head = Helmet.rewind();
            res.status(200).send(head.title.toString()+head.meta.toString());
    });
});

var PORT = process.env.PORT || 8081;
app.listen(PORT, () => console.log('Running on port ' + PORT));
```
Any idea on how I could debug that ?

**Comment by bguiz** [comment]
@yukulelix Yeah, I'm getting empty strings rendering in exactly the same way as you, with the only difference being that I'm using `renderToStaticMarkup()` instead of `renderToString()`, like so:

```
let rendered = ReactDomServer.renderToStaticMarkup(
        <RouterContext {...renderProps} />);
helmet = Helmet.rewind();
```

@doctyper I assume you're referring to [this snippet](https://github.com/nfl/react-wildcat/blob/7f8181e85a4b339e15d9c704aca5ccadf88596cf/packages/react-wildcat-handoff/src/utils/serverRender.js#L55-L63)? Thanks for the heads up, I'll try to see if I can spot where I'm stuffing up!

**Comment by bguiz** [comment]
OK, so I've got to the bottom of this issue (at least in my case)... it was that `Helmet.rewind()` is a static method call, which is totally fine if you only include it in one place as a dependency. If there's more than one, swap it over to `peerDependencies` - or otherwise ensure that you are using the same instance - and works as expected.

Not sure if the cause is the cause is the same for you, @madpilot and @yukulelix but I'm closing this issue. Ask @doctyper  to re-open if this is the case!

W: http://bguiz.com

**Comment by yukulelix** [comment]
Thx @bguiz , it works now.
I was compiling my server and client javascript using different environment !
Regrouping them using multi-compiler feature of Webpack fixed it !
Cheers

**Comment by asiniy** [comment]
@bguiz could you explain this situation? I adeed `react-helmet 3.1.0` to peerDependencies to my package.json. Nothing happens unfortunately

**Comment by bguiz** [comment]
@asiniy The root cause of the problem (at least for me) was that there are multiple instances of react-helmet being loaded. Therefore any global static state would have multiple copies, and behave incorrectly. In my case, the solution was to ensure that there was only one copy of react-helmet in my dependency graph, and I achieved this using peer dependencies. The solution in your case may not be the same, but you might have some luck by making sure to remove all but one copy of react-helmet.

**Comment by kenfehling** [comment]
So you're not doing `import Helmet from 'react-helmet'` in the server? You're importing an instance from a file in your "client" app code?

**Comment by phyllisstein** [comment]
Something like that! My Webpack configuration creates two builds, one for the client and one for the server. The server entrypoint looks like this:

```js
import 'babel-polyfill'

export { A, buildStore } from 'app/flux'
export { App } from 'app/views'
export { flushWebpackRequireWeakIds } from 'react-loadable'
export Helmet from 'react-helmet'
```

Since _that_ winds up being the instance of Helmet that accumulates state when I render `App`, that's the one I have to import and call `renderStatic()` on when I want to get that state back out.

**Comment by raubas** [comment]
I had exactly the same problem with React router v4 with SSR.

THIS WAS A LIFESAVER!!!

in my `./Application.js` which is wrapped by a browser-router for the web and a static router for the server,

did:
`export const AppHelmet = Helmet`

and used that all over the app and also for where I did `AppHelmet.renderStatic()`

**Comment by aemoe** [comment]
@phyllisstein  @raubas @kenfehling 
Thank for your advise.
I found a  way to resolve this problem. Use the same node_modules.
Use the client's helmet , it works very well. Below:
```js
import {Helmet} from '../../client/node_modules/react-helmet';

export function index(ctx) {
        const store = configureStore(loginStore);

        renderToStaticMarkup(<Provider store={store}>
          <StaticRouter location={ctx.url} context={{}}>
            <App/>
          </StaticRouter>
        </Provider>);
        const helmet = Helmet.renderStatic();
        console.log('title',helmet.title.toString());
  }
}
```

**Comment by BorodinDK** [comment]
I just added this line `externals: ["react-helmet"],` to webpack server config, It works!
