### ISSUE TITLE
Duplicate og:url tags

### ISSUE THREAD

**Issue by DanCech** [nfl/react-helmet#138]
I recently ran into an issue when trying to set the og:url meta tag dynamically.  I have a Helmet tag in my main App container and am trying to dynamically set the og:url meta tag based on the browser location.

The issue comes up when you start navigating on the front-end, as each page adds a new og:url meta tag rather than overwriting the existing one (presumably because they're being generated by the same Helmet component).

One potential solution that came to mind was to add the ability to flag a meta item and force it to override any previous instances of that item, so I could specify it like:
```
<Helmet meta={[{property: 'og:url', content: dynamicUrl, override: true}]} />
```
Is there an existing way to work around this type of problem that I'm just missing?

**Comment by cwelch5** [comment]
@DanCech With the meta tag, `property` is a unique identifier, which should guarantee that there is only one of that particular kind.  As you change routes, there should only be one `og:url` property at a time.

This `override` idea may apply to other tags, and I'm actively brainstorming a way for this to work seamlessly for everyone.  Your particular use case should work.

**Comment by DanCech** [comment]
Strange, I'll have to see if I can cut it down to a small example, I was definitely seeing the og:url tags stacking up rather than getting overridden.

**Comment by DanCech** [comment]
Figured it out, the code was actually mutating the source array of meta tags instead of appending the og:url item to a local copy.  Sorry for the noise.
