### ISSUE TITLE
Componentize Helmet

### ISSUE THREAD

**Issue by doctyper** [nfl/react-helmet#142]
Now that we are covering the [full suite of elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head) that can be used in `<head>`, it might be time to think about componentizing (is that a word?) Helmet. Having so many potential properties in one `<Helmet />` tag makes it look a little long in the tooth. @potench suggested this nested API as a possibility:

```
<Helmet>
    <Title>
    <Meta>
    <Script>
</Helmet>
```

Thoughts?

**Comment by mattecapu** [comment]
I'd go with 
```html
<Helmet.Head>
    <Helmet.Title>
    <Helmet.Meta>
    <Helmet.Script>
</Helmet.Head>
```
To better distinguish the components from the plain HTML tags

**Comment by doctyper** [comment]
Done via #246.
