### ISSUE TITLE
htmlAttributes is undefined

### ISSUE THREAD

**Issue by collinglass** [nfl/react-helmet#144]
I am defining my app based off the example in the README:

```
return (
      <div className={styles.app}>
        <Helmet
          htmlAttributes={{'lang': lang, 'amp': undefined}}
          titleTemplate={i18next.t('title', {lng: lang})}
          meta={[
            {name: 'keywords', content: i18next.t('keywords', {lng: lang})},
            {name: 'description', content: i18next.t('desc', {lng: lang})},
            {name: 'google', content: 'notranslate'},
            {charset: 'utf-8'},
            ...
```

I get an undefined error on htmlAttributes and when I console.log I get the following:

HTML output:

{ title: { toComponent: [Function], toString: [Function] },
   base: { toComponent: [Function], toString: [Function] },
   meta: { toComponent: [Function], toString: [Function] },
   link: { toComponent: [Function], toString: [Function] },
   script: { toComponent: [Function], toString: [Function] } }

Is there any reason that only 5/7 properties are present?
Does anyone have any idea why this is?

**Comment by doctyper** [comment]
You may be using an outdated version of Helmet.

**Comment by collinglass** [comment]
Yep I had an outdated version specified in my package.json. -_- Closing
