### ISSUE TITLE
Strange behaviour for title on server-side/client

### ISSUE THREAD

**Issue by romanonthego** [nfl/react-helmet#151]
since i've update to `3.1.0` strange bug appear:

When rendered on server-side page provide correct title: 
![](http://take.ms/3gmNg)
But then I navigate to very same page on client (`react-router` and stuff):
![](http://take.ms/lgcCF)
Despite `react-devtools` telling me `title` prop is in fact passed down correctly:
![](http://take.ms/Vt0RI)

Any ideas?

**Comment by romanonthego** [comment]
ok, nevermind, _fixed_ (well, found conflict) 👌

**Comment by fedgrant** [comment]
What was your conflict? I am also seeing some odd behavior with react-router.

**Comment by romanonthego** [comment]
Nope, just second module with side-effect messed up with document title
under certain conditions. Nothing to do with react-router, everything fine
now (we do use react-router@2.0 )
