### ISSUE TITLE
noscript tag support

### ISSUE THREAD

**Issue by chrisblossom** [nfl/react-helmet#152]
Is `<noscript />` tag support planned?

Thank you!

**Comment by kenleytomlin** [comment]
@cwelch5 First of all thanks for the great work you have done on this module.  
Can we get the noscript support into a release?  The code has been merged but isn't available on npm and installing from git is causing my webpack build to fail.

**Comment by cwelch5** [comment]
@kenleytomlin Thanks for your patience.  This is available in v3.2.0.
