### ISSUE TITLE
How do I use this with python-react?

### ISSUE THREAD

**Issue by jinxac** [nfl/react-helmet#153]
I was trying to use helmet for changing meta tags on the fly but the meta tags dont come in the page source and because of that when i try sharing on that on facebook, fb scraper does not pick it up.

Please check my page out once for the details www.harkiratsaluja.com

**Comment by cwelch5** [comment]
Are you using rewind in your server-side render? Could we see your code?

**Comment by jinxac** [comment]
I think i will go ahead and close this issue , I was using client side react and not on server, so none of the components would come on the view source , I am right now trying to do this with react-django library, will update the findings. Till then I will close the issue.

**Comment by jinxac** [comment]
So i tried using this with python-react but getting little confused on where to call rewind() function?

Following is my sample code:-

**example.py**

@app.route('/')
def index():
    rendered = render_component(
        os.path.join(os.getcwd(), 'static', 'js', 'CommentBox.jsx'),
        {
            'comments': comments,
            'url': '/comment/',
        },
        to_static_markup=True,
    )
    return render_template('index.html', rendered=rendered)

**CommentBox.jsx**

import React from 'react';
import Helmet from 'react-helmet';

import CommentList from './CommentList.jsx';
import CommentForm from './CommentForm.jsx';

class CommentBox extends React.Component {
        render() {
                return (
                        <div>
                                <Helmet
                    title="About"
                    meta={[
                        {property: 'og:image', content: 'http://www.gettyimages.pt/gi-resources/images/Homepage/Hero/PT/PT_hero_42_153645159.jpg'},
                    ]} />
                                <CommentList comments={this.props.comments} />
                                <CommentForm url={this.props.url} />
                        </div>
                );
        }
}

export default CommentBox;

Now, i need to call rewind() as mentioned in the docs, from where do I call that?

**Comment by doctyper** [comment]
`Helmet.rewind()` needs to be called in Node for it to work. It is a singleton, meaning it must share context with React to behave properly.

In your example you are attempting to call it in a Python context, which is not going to work. You will need to figure out how to call `rewind()` inside `python-react`. I would post this question in [markfinger/python-react](https://github.com/markfinger/python-react).
