### ISSUE TITLE
Unfurling on social sites doesn't display title 

### ISSUE THREAD

**Issue by xiutxu** [nfl/react-helmet#157]
If I add this to my jsx
```
          <Helmet
            title="helmet:title"
            meta={[
              {"property": "og:title", "content": "og:title" },
              {"property": "twitter:title", "content": "twitter:profile" }
            ]}
          />
```
The title of the page as shown in browser tab is "helmet:title". However, when I share it on a social channel such as Slack, Discord, or Twitter, the title isn't that. Has there been any work on making social tags play nicely with Helmet or am I missing something. If I am missing something, I would love to know! 

Thank you for making this available for people like myself. This should end up saving me a little time and my code a little cleaner!

**Comment by cwelch5** [comment]
@xiutxu Thanks for you interest in Helmet!  What is the title on social channels for your particular example?  Do you have server side rendering in your React application?

**Comment by xiutxu** [comment]
HI @cwelch5 that was quick! I was using `og:title`, `twitter:profile`, and `helmet:title` just to see which would be rendered from the component. The title is dynamic based on the resource loaded from within a component. I am rendering server side, and I'm not entirely sure if this is the _best_ way to do things, but I got around it with this snippet for my express server:

```
      request(url)
      .then(function(body) {
          var resource = JSON.parse(body);
          var html = ReactDOMServer.renderToStaticMarkup(htmlComponent({
            markup: ReactDOMServer.renderToString(bodyElement),
            preview: true,
            image: resource.thumb,
            title: resource.title
          }));
      ...
```

**Comment by cwelch5** [comment]
@xiutxu I don't see your call to `rewind()`, which will retrieve your `head` attributes that you can then render as components or strings.  Check out the README which has more info on this; I think that'll get things working for you.

**Comment by xiutxu** [comment]
Thanks @cwelch5. I missed that completely!
