### ISSUE TITLE
Better page speed

### ISSUE THREAD

**Issue by caranicas** [nfl/react-helmet#159]
I am wondering how to increase my google PageSpeed numbers for a boilerplate I contribute to. 

currently my biggest hit is 

> Should Fix:
> Eliminate render-blocking JavaScript and CSS in above-the-fold content

I am using the link attribute to house my style tags, and Originally it was in the header with my meta and title info, so this made sense. 

```
<head>
  ${header.title.toString()}
  ${header.meta.toString()}
${header.link.toString()}
</head>
```

So I tried moving it down to just below the closing body tag. Like this. 

```
<body>
  <div id="app">${componentHTML}</div>
  <script>window.__INITIAL_STATE__ = ${JSON.stringify(initialState)};</script>
  <script type="text/javascript" charset="utf-8" src="/assets/app.js"></script>
  ${header.link.toString()}
</body>
```

But PageSpeed Insights still throws the same issue. 

Any advice would be great. thanks!

**Comment by cwelch5** [comment]
When you see the server side rendering, does it put the link tags at the bottom of the body as you expect?  Passed that, I'm not sure if that's best practice, or why PageSpeed is still throwing that error for you.

**Comment by caranicas** [comment]
yes, when I move the link down to the bottom I do see it rendered down at the bottom. I believe this is the best practice. I wasn't sure if Page speed was something you had concerned yourself with yet, and just thought I would bring it up.

**Comment by cwelch5** [comment]
Looking at this again, I have a hunch that PageSpeed is smart enough to render your page fully including a client side rendering.  This may explain why the script is still in the head, because the current behavior of Helmet will re-render on the client side putting the script back in your head.

This enhancement may solve your issue - #141

**Comment by mgreer** [comment]
add "defer" or "async" to the app.js, so it loads and executes after the body.

**Comment by cwelch5** [comment]
If `defer` or `async` doesn't work, the duplicate issue will most likely fix as the link will ideally stay in it's server-side rendered location.
