### ISSUE TITLE
Mark some tags "frozen"

### ISSUE THREAD

**Issue by janoist1** [nfl/react-helmet#161]
On server side I add some extra tags with Helmet but the client removes them so that some CSS styles disappear ..
It'd be nice to be able to mark some tags "frozen" or something .. Any idea?

**Comment by cwelch5** [comment]
Is this still an issue for you?  There's no way to mark "frozen" tags yet.  This may be related to a current bug we have.  What is exactly happening?

**Comment by cwelch5** [comment]
Based on your description, this describes #149 , closing as duplicate.
