### ISSUE TITLE
Tags handling fail with null value

### ISSUE THREAD

**Issue by matthewheck** [nfl/react-helmet#162]
I'm pulling data from a database and then plugging it into Helmet like so:

```
<Helmet
    htmlAttributes={{ lang: data.language }}
    title={data.title}
    titleTemplate={`%s | ${data.title}`}
    defaultTitle={data.title}
    meta={[
        { name: 'description', content: data.description },
    ]}
    link={[
        { rel: 'apple-touch-icon', href: data.apple_touch_icon },
        { rel: 'icon', sizes: '192x192', href: data.favicon },
    ]} />
```

Some of these values may come back as `null` if the user has not provided them yet. This leads to an error trying to manipulate tags (in the meta and link) `toLowerCase` (here)[https://github.com/nfl/react-helmet/blob/17eb00abcf71d57f51827575d37c2ae8ed9997fb/src/Helmet.js#L99].

There are multiple potential solutions here that could be implemented on my end, from changing the return from the database to be empty strings, to programmatically replacing `null`s with empty strings before running it through Helmet, and more. But, I was thinking it might be better to find an appropriate handling of `null` values in the `getTagsFromPropList` function.

Happy to implement if you all think this is acceptable and we find a good approach!

**Comment by cwelch5** [comment]
@matthewheck Thanks for your interest in Helmet.  Yes, just like if you pass in an empty string, that tag won't get rendered; it should also handle null values.  If you'd like to work on a PR we'd appreciate it.

**Comment by rwillrich** [comment]
Hi,

I have the same error. But in my case it is even worse! The error occurs on `Helmet.rewind()` and it does not clear the react-side-effect data. So, after the first error happen, every call of `Helmet.rewind()` will have the same error.
