### ISSUE TITLE
New pull request about itemprop in meta and title tag

### ISSUE THREAD

**Issue by dattran92** [nfl/react-helmet#163]
I'm implementing "itemprop" attribute in meta and title tag in my project.
I think the feature may benefit many people since It's necessary for SEO. 
So if you feel OK, I will make a pull request for this implementation.

**Comment by cwelch5** [comment]
That sounds great.  Could we continue the discussion in #113 ?

Could you also explain the title tag case, because some quick searching I couldn't find any examples.
