### ISSUE TITLE
Using titleTemplate strips out $ characters when multiple are present

### ISSUE THREAD

**Issue by neilius** [nfl/react-helmet#164]
I have a site using the `titleTemplate` prop and when using it, it causes a string containing multiple instances of $ to get stripped out. For example,

`<Helmet title="neiliu$$" />` renders as `<title>neiliu$</title>` when the `titleTemplate` prop is set on my parent Helmet component.

It appears that this is what's happening https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter

**Comment by cwelch5** [comment]
Thanks. This is available in v3.2.0.
