### ISSUE TITLE
How to unit test an application that uses Helmet?

### ISSUE THREAD

**Issue by templth** [nfl/react-helmet#168]
Is there a way to unit test an application that uses Helmet? The problem is that Helmet sets things outside the current component...

Thanks very much for your help!

**Comment by cwelch5** [comment]
@templth Thanks for your interest in Helmet.  Yes, true, Helmet only deals with side effects to the document head.  There a couple ways to approach testing.  You can certainly set assertions that check for conditions in your document head.  You can also utilize `onChangeClientState` callback to monitor state changes as Helmet processes them.

I hope that helps.

**Comment by templth** [comment]
@cwelch5 Thanks very much Chris for your answer!

Here is a fake component using Helmet I want to test:

```
class FakeComponent {
	render() {
		return (
			<div>
				<Helmet
					onChangeClientState={ this.logChangeClientState }
					title={"Test Title"}
					defaultTitle={"Fallback"}
				/>
			</div>
		)
	}
	logChangeClientState() {
		console.log('logChangeClientState');
	}
}
```

and here is the test I implemented (with Mocha and Enzyme):

```
it('fake test', function() {
	let wrapper = shallow(
		<div><FakeComponent/></div>
	);
	console.log('title = ', document.title);
});
```

`document.title` is empty and `logChangeClientState` isn't called. I think that I missed something.

Thanks very much for your help!

**Comment by cwelch5** [comment]
It seems like Helmet is not getting rendered.  What does `shallow` do?  Is it like this - https://facebook.github.io/react/docs/test-utils.html#shallow-rendering?  If that's the case, from how I'm reading this, it only renders the first level, and may not be rendering Helmet.  Try doing a `ReactDOM.render` of the Helmet component and see if that helps.

**Comment by doctyper** [comment]
You'll need to use [`mount`](https://github.com/airbnb/enzyme/blob/master/docs/api/mount.md), which will recreate a DOM for you so you can query it in your test. You might also need to query the title in the mounted component itself (`wrapper.find("title")`).

**Comment by templth** [comment]
Thanks very much, guys! It works fine ;-)

**Comment by dimaqq** [comment]
Does this still work?
Somehow the following fails for me, and it looks basically the same:

```js
// src/nav.spec.js
import React from "react";
import Helmet from "react-helmet";
import { mount } from "enzyme";
import "should";
import "should-enzyme";


it("foo", () => {
  const page = mount(
    <div>
      <Helmet>
        <title>foobar</title>
      </Helmet>
    </div>);
  document.title.should.eql("foobar");
});
```

fails with:

```
 FAIL  src/nav.spec.js
  ● foo

    AssertionError: expected '' to equal 'foobar'

      13 |       </Helmet>
      14 |     </div>);
    > 15 |   document.title.should.eql("foobar");
         |                         ^
      16 | });
      17 |
      18 |

      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at Object.eql (src/nav.spec.js:15:25)
```

**Comment by brainlessdeveloper** [comment]
Found an answer to this in the following SO question: https://stackoverflow.com/questions/44073960/unit-testing-react-helmet-code

```typescript
    const wrapper = mount(<Metadata/>);
    // this will return all the markup assigned to helmet
    // which will get rendered inside head.
    const helmet = Helmet.peek();
    expect(helmet.title).to.equal("title");
```

**Comment by Primajin** [comment]
If you want to test helmet with only jest and no furhter modules like enzyme etc. you can do the following:

add:
```js
jest.mock('react-helmet', () => {
	const React = require('react');
	const plugin = jest.requireActual('react-helmet');
	const mockHelmet = ({children, ...props}) =>
		React.createElement('div', {
			...props,
			className: 'mock-helmet',
		}, children);
	return {
		...plugin,
		Helmet: jest.fn().mockImplementation(mockHelmet),
	};
});
```

to your `setupFiles` in the jest config.

Now it will render a `<div className="mock-helmet">` that you can use for snapshot tests or inspect further and check if a certain `<meta>` tag is present inside.

**Comment by Bccorb** [comment]
> If you want to test helmet with only jest and no furhter modules like enzyme etc. you can do the following:
> 
> add:
> 
> ```js
> jest.mock('react-helmet', () => {
> 	const React = require('react');
> 	const plugin = jest.requireActual('react-helmet');
> 	const mockHelmet = ({children, ...props}) =>
> 		React.createElement('div', {
> 			...props,
> 			className: 'mock-helmet',
> 		}, children);
> 	return {
> 		...plugin,
> 		Helmet: jest.fn().mockImplementation(mockHelmet),
> 	};
> });
> ```
> 
> to your `setupFiles` in the jest config.
> 
> Now it will render a `<div className="mock-helmet">` that you can use for snapshot tests or inspect further and check if a certain `<meta>` tag is present inside.

You are a lifer saver!

**Comment by eudoroolivares2016** [comment]
Using the `.peek()` method works for me for testing but, I don't understand where that's coming from.  I don't see it referenced anywhere in the API
`
const helmet = Helmet.peek()
expect(helmet.titleTemplate).toEqual('title')
`
