### ISSUE TITLE
Upstream changes to react-side-effect

### ISSUE THREAD

**Issue by necolas** [nfl/react-helmet#17]
You could externalise your side-effect module by applying it to react-side-effect as a fix for https://github.com/gaearon/react-side-effect/issues/4

**Comment by cwelch5** [comment]
Thanks, yes, I had started that PR to take the management of that dependency out of this library.  And yes, we've changed it a bit since then, so I updated my fork and updated the PR.  Thanks for looking out.

Here's the updated PR: https://github.com/gaearon/react-side-effect/pull/5

**Comment by cwelch5** [comment]
We've externalized react-side-effect, and are using the latest version.  Reflected in Helmet 1.1.3
