### ISSUE TITLE
Help on render MetaTags on children

### ISSUE THREAD

**Issue by MarcosSilvaAv** [nfl/react-helmet#178]
I have this routes.js, 

on EventResultAthlete Meta Tags not being render on source code, i test the scrapper on Home, NewRead, EventHome and other pages and i have no problem with this, if i test on EventResultAthlete i can´t retrive anything.

What code more do u need more to help me with this problem

Sry for my bad english xD

```
<Route path="/:lang" component={App}>
    <Route path="home" component={Home} /> 
    <Route path="page/:pageContent" component={Content} />
    <Route path="event/list" component={EventCalendar} />
    <Route path="event/list/:eventYear" component={EventCalendar} />
    <Route path="event/list/:eventYear/:eventMonth" component={EventCalendar} />
    <Route path="event/:eventAlias" component={EventPage}>
      <IndexRoute component={EventHome} />
      <Route path="athlete/:dorsal" component={EventResultAthlete} />
    </Route>
    <Route path="news/:newAlias" component={NewRead} />
    <Route path="contacts" component={Contacts} />
    <Route path="budgetRequest" component={BudgetRequest} />
    <Route path="*" component={Error404} />
 </Route>
```

**Comment by cwelch5** [comment]
When you visit this route - `<Route path="athlete/:dorsal" component={EventResultAthlete} />` - you aren't seeing the meta tags render?  On client side, server side, or both?  What does your Helmet configuration look like on that component?

**Comment by MarcosSilvaAv** [comment]
On that component(not working) - Client on Left - server on  right -> http://cloud.nexus-pt.eu/owncloud/index.php/s/ahiA5l76DeqBkdq

Component -> http://cloud.nexus-pt.eu/owncloud/index.php/s/TcoemRv7TZGzj8Q

Server.js -> http://cloud.nexus-pt.eu/owncloud/index.php/s/VZrvesMyE2GtuKc

On Component Home - Client on Left - server on  right -> http://cloud.nexus-pt.eu/owncloud/index.php/s/TNtlnNvkEeiWRzM

**Comment by cwelch5** [comment]
@MarcosSilvaAv Thanks for your patience, is this still an issue for you?  I think those links you provided may have expired.

**Comment by MarcosSilvaAv** [comment]
No worry, thanks for the help.

I got it. Missplaced code on server.js.

Thanks =)
