### ISSUE TITLE
Problem with unicode as meta description content

### ISSUE THREAD

**Issue by beeant** [nfl/react-helmet#18]
I'm having problem with using Japanese texts for meta description.
Seems that the problem is caused by HTMLEntities.encode.

**Comment by cwelch5** [comment]
I tried some Japanese text and it encoded it correctly.  Server and client side look correct.

Do you have a specific example that is not working for you?

**Comment by geekyme** [comment]
hey @cwelch5 I am having the exact same issues with chinese text. 
You can [view source](view-source:https://tw.carousell.com/?hl=zh-TW)

**Comment by geekyme** [comment]
Why is there a need to encode here? https://github.com/nfl/react-helmet/blob/master/src/Helmet.jsx#L142

**Comment by doctyper** [comment]
@geekyme

```js
<Helmet title="<script>alert('xss!')</script>" />
```

**Comment by geekyme** [comment]
@doctyper then the title generated on the server side becomes this: 

```
<title>&amp;#x62CD;&amp;#x7167;&amp;#x5373;&amp;#x8CE3;&amp;#x3001;&amp;#x79C1;&amp;#x8A0A;&amp;#x53CA;&amp;#x8CB7;&amp;#xFF0C;&amp;#x514D;&amp;#x8CBB;&amp;#x62CD;&amp;#x8CE3;&amp;#x5E73;&amp;#x53F0;&amp;#x5C31;&amp;#x5728;Carousell&amp;#x65CB;&amp;#x8F49;&amp;#x62CD;&amp;#x8CE3;&amp;#xFF01;</title>
```

**Comment by geekyme** [comment]
I think you should try something like https://github.com/yahoo/xss-filters instead. This issue should also be reopened because it has not be solved.

**Comment by potench** [comment]
The Chinese character set displays correctly when rendered in the browser but is served as html-entities.  @geekyme what's your primary concern here? I'm not sure if this would affect SEO. 
I believe we could swap the `HtmlEntitityEncoding` with underscores `escape` to strip encode only special-characters.  http://underscorejs.org/#escape

**Comment by geekyme** [comment]
It would cause problems with SEO and also causes issues with google analytics showing page titles as the HTML entities instead of real characters. Users might get confused too because their page title flashed from HTML entities to Chinese characters.

**Comment by potench** [comment]
@geekyme 2.1.1 should fix this.
