### ISSUE TITLE
Without server.js

### ISSUE THREAD

**Issue by drebbits** [nfl/react-helmet#180]
Hi,

I have a question, can this be used without server.js (server side rendering)? My head is added via plain html. Well, actually its in a php file. I see there's a server.js in the example to use the `.rewind()`.

Thanks!

**Comment by drebbits** [comment]
Sorry this is more of question..

**Comment by cwelch5** [comment]
Sorry for the very delayed response.  Yep, you can definitely use Helmet client side only.  Sever side rendering is optional.  If you are having any problems getting it working, let us know.
