### ISSUE TITLE
Allow meta tags to be seen by Facebook & Twitter scraper

### ISSUE THREAD

**Issue by RichardJECooke** [nfl/react-helmet#181]
My meta tags that I set with Helmet can be seen in the page inspector in my browser devtools, but not in the page source (because they're set dynamically in React obviously). So Facebook's share function doesn't see them if I share my page.

Does this mean Helmet (and any React meta tags) cannot be used for social media sharing?  Is there a workaround?

(Our website is a React app separate to the server, not like this guy: https://github.com/nfl/react-helmet/issues/26)

**Comment by cwelch5** [comment]
Hi @RichardJECooke, Helmet can only be used for social media sharing if used on the server.  Because that is what the page scraper will see.  If you are using client side only, you can still take advantage of all the great declarative organization in your document head that Helmet offers.

**Comment by jotto** [comment]
@RichardJECooke @cwelch5 I had this problem (social media sharing not picking up the tags) and just launched https://headless-render-api.com/ to solve it

**Comment by cjimmy** [comment]
I wrote a brief summary of options, including @jotto's tool, back in #26 

https://github.com/nfl/react-helmet/issues/26

**Comment by ademidun** [comment]
> I wrote a brief summary of options, including @jotto's tool, back in #26

Thanks @cjimmy, here is the specific comment: https://github.com/nfl/react-helmet/issues/26#issuecomment-339128792
