### ISSUE TITLE
[Question] Is there any way to manage application body classes with Helmet?

### ISSUE THREAD

**Issue by mmmeff** [nfl/react-helmet#182]
Title ^

**Comment by cwelch5** [comment]
No, sorry, Helmet is meant to manage your document head.  I assume you are referring to classes on the body tag? - `<body class="application test"> ...`

**Comment by mmmeff** [comment]
Bummer. Helmet would be perfect for such a thing.

**Comment by cwelch5** [comment]
Actually this could be something we consider, we did open up attributes for the html tag.  We could extend it to support body attributes.  Great idea.  Curious, do you have a particular use case?

**Comment by mmmeff** [comment]
Lots! Body classes are an awesome way to control core layout changes of an application. For example, I have a few pages of my app that need a full-screen header treatment instead of a singular centered-column. For example, the user can switch from a search results list to a search results map view - a much more full-screen layout.

The page component I wrote is extended by each page, and part of the constructor involves calling `super(props, ['fullscreen-header'])` where the `Page` base class applies these classes to body during ComponentDidMount (amongst many other things). 

It's a workable solution, but I'd love to get these body classes integrated into my server-side rendering to avoid the split second where the body class isn't applied on load. Doing so would require me to rework a solution that would ideally be similar to how we're using Helmet for meta/title information, but I'd hate to reinvent the wheel there.

I suppose I could use <html> attributes to achieve this instead of body classes though

**Comment by cwelch5** [comment]
@mmmeff I think you are correct about using attributes or potentially serving a different style sheet per the layout that you want.

For now, we'd like to keep this library focused mainly on the document head.  Thanks.

**Comment by jmatsushita** [comment]
Just thought I'd mention that I was interested in this feature as well for the same reason (applying classes to the `body` element to swap to a full screen mode).

**Comment by codepunkt** [comment]
I'll add myself to the queue of people interested in setting body classNames.

**Comment by cwelch5** [comment]
Helmet now supports classes to `<html>`, does that work for you? @codepunkt

**Comment by codepunkt** [comment]
Amazing, that should work! Thanks @cwelch5!
How do you do it, using the `htmlAttributes`?

**Comment by cwelch5** [comment]
👍

**Comment by stefvhuynh** [comment]
Was looking for something for this and came across this: https://www.npmjs.com/package/react-body-classname

Might be helpful. :)

**Comment by codepunkt** [comment]
@stefvhuynh If i absolutely had to use body classNames, that would probably be a good option. As i was using `react-helmet` anyway, i switched to setting html classNames using `htmlAttributes` so that i wouldn't need another dependency.

**Comment by stefvhuynh** [comment]
@codepunkt, yeah that makes sense. In my situation, the body class was necessary as it was a transition project, so I ended up using my own version of the package I pointed to with some modifications.

**Comment by Richacinas** [comment]
> Was looking for something for this and came across this: https://www.npmjs.com/package/react-body-classname

@stefvhuynh Careful with that one, make sure you call rewind, otherwise you'll get a BIG memory leak:

> Important: This component keeps track of mounted instances, so if you don't call BodyClassName.rewind() you'll get a memory leak.

**Comment by liamhession** [comment]
There is at this point (for quite a while now but apparently not at the time this thread was active) a `bodyAttributes` attribute to the main `Helmet` object, so you can add classes to the body for a particular page. https://github.com/nfl/react-helmet/blob/2aecac5d0df4bc208fb11394e867b1b1ddcd5a5f/src/Helmet.js#L35

**Comment by liamhession** [comment]
And strangely enough, i found that for it to work right when running my site with `gatsby develop`, i needed to pass it in like:
```
bodyAttributes={{ class: 'landing-page-body' }}
```
instead of saying `className` as you'd expect to do based on the comments in react-helmet. And using `class` instead also works when the site is built by Gatsby, so that's what i'm going with
