### ISSUE TITLE
Ability to forego encoding

### ISSUE THREAD

**Issue by imjared** [nfl/react-helmet#184]
We're dynamically creating images via imgix to be used in og:image tags on Facebook for our Gatsyby.js-based site. Here is what a URL should look like (brace yourself): 

`https://cfe.imgix.net/img/share-base.png?mark64=aHR0cHM6Ly9jZmUuaW1naXgubmV0L350ZXh0P3R4dD1OYXNzYXUrc2Nob29sJnc9OTAwJmg9MjAwJmJnPTAwMDAwMDAwJnR4dGNscj1GRjI2ODQ4MiZ0eHRzaXplPTY1JnR4dGZvbnQ2ND1RWFpsYm1seUxVSnNZV05yJnR4dHRyYWNrPTAmdHh0YWxpZ249bGVmdCx0b3A=&markx=27&marky=100&blend64=aHR0cHM6Ly9jZmUuaW1naXgubmV0L350ZXh0P3R4dD0gJCA0NDgsMDAzICZ3PTExNDAmaD0xNjAmYmc9MDAwMDAwMDAmdHh0Y2xyPUZGRkZGRkZGJnR4dHNpemU9ODAmdHh0Zm9udDY0PVFYWmxibWx5TFVKc1lXTnImdHh0dHJhY2s9MCZ0eHRhbGlnbj1sZWZ0LHRvcA==&bx=27&by=300&bm=normal`

When we run our URLs through react-helmet, it URL-encodes everything and we get a lot of `&amp`. Here's what we get:

`https://cfe.imgix.net/img/share-base.png?mark64=aHR0cHM6Ly9jZmUuaW1naXgubmV0L350ZXh0P3R4dD1OYXNzYXUrc2Nob29sJnc9OTAwJmg9MjAwJmJnPTAwMDAwMDAwJnR4dGNscj1GRjI2ODQ4MiZ0eHRzaXplPTY1JnR4dGZvbnQ2ND1RWFpsYm1seUxVSnNZV05yJnR4dHRyYWNrPTAmdHh0YWxpZ249bGVmdCx0b3A=&amp;markx=27&amp;marky=100&amp;blend64=aHR0cHM6Ly9jZmUuaW1naXgubmV0L350ZXh0P3R4dD0gJCA0NDgsMDAzICZ3PTExNDAmaD0xNjAmYmc9MDAwMDAwMDAmdHh0Y2xyPUZGRkZGRkZGJnR4dHNpemU9ODAmdHh0Zm9udDY0PVFYWmxibWx5TFVKc1lXTnImdHh0dHJhY2s9MCZ0eHRhbGlnbj1sZWZ0LHRvcA==&amp;bx=27&amp;by=300&amp;bm=normal`

 While I'm praising you for doing this for me, I'm kind of 😕  at imgix for not allowing `&amp;` Regardless, we need to figure out a way to only pass `&` through and ensure it doesn't encode to `&amp;`

I totally get @doctyper's [concern for unescaped strings being an XSS attack vector](https://github.com/nfl/react-helmet/issues/18#issuecomment-150258758) but in this case, we're not rendering user content, we're rendering static content on the server.

Is there:
a. A workaround
b. Any interest in this functionality. A PR might consist of an option like `__dangerouslySetUnencodedString={...}` (really creative naming here, I know).

**Comment by potench** [comment]
Why don't you use a URL shortener to created a permanent redirect to this image?

**Comment by imjared** [comment]
That's a good idea, and certainly one I hadn't thought of, but we're dynamically creating 4000+ URLs on the front-end. Ideally, we would have the "don't encode" option available for use rather than having to write a script to run them all through goo.gl's link-shortener API.

**Comment by IchabodDee** [comment]
@imjared Did you end up getting around this?

I am doing a similar thing with imgix. 

Thanks!

**Comment by imjared** [comment]
@IchabodDee As a quick fix, I forked and removed the encoding function entirely: https://github.com/imjared/react-helmet

Not the best approach but it was quick and worked.

**Comment by doctyper** [comment]
@imjared This is now supported in [Helmet 5](https://github.com/nfl/react-helmet#reference-guide):

```js
<Helmet encodeSpecialCharacters={false}>
    ...
</Helmet>
```

**Comment by alexandrunemes** [comment]
I know encodeSpecialCharacters is set to true by default, but it doesn't do anything for me. The special characters that are supposed to be replaced with their htmlentities still appear in the meta tags when I inspect the DOM. 
What could be the problem, @doctyper ?

Thanks!

**Comment by doctyper** [comment]
Could you provide a reproducible test case? It’s possible we didn’t carry over the functionality in our legacy method.
