### ISSUE TITLE
Accessing 'head' after rewind

### ISSUE THREAD

**Issue by oojacoboo** [nfl/react-helmet#193]
I'm trying to figure out how, with `react-server`, you can access the `head` variable from within a `<head>` component that's part of `react-router`?  Is this passed as a prop from HoC?  If so, I can't see to access it as such.

Is that because it's not available on a first pass and then it's available from a `rewind`?  If so, I'm guessing I'd need to define the `head` defaults?

Please advise, the documents we're very clear in how the `head` variable is accessed or passed around.  Thanks!

**Comment by cwelch5** [comment]
Hi @oojacoboo, sorry for the delayed response.  After rendering your app on the server using `ReactDOM.renderToString` or `ReactDOM.renderToStaticMarkup`, then use the static function `rewind` on Helmet to get your helmet data to render on the server - https://github.com/nfl/react-helmet#server-usage

I'm not familiar with `react-server`, but poking around quick, you need to access `Helmet.rewind` after this runs https://github.com/redfin/react-server/blob/master/packages/react-server/core/renderMiddleware.js#L817

Hope that helps.
