### ISSUE TITLE
canUseDOM no longer working

### ISSUE THREAD

**Issue by JakeGinnivan** [nfl/react-helmet#195]
When upgrading to 3.2.1 all my tests broke, assuming because `Helm.canUseDOM = false` is no longer being respected.

Downgrading to 3.1.0 fixes the error `Error: You may ony call rewind() on the server. Call peek() to read the current state.`

My tests use JSDom and Enzyme so I need to turn off the check for the DOM.

**Comment by cwelch5** [comment]
I'm in the midst of reverting.  Sorry for the inconvenience.

**Comment by cwelch5** [comment]
fixed in v3.2.2

**Comment by JakeGinnivan** [comment]
Awesome, thanks :)
