### ISSUE TITLE
Remove `shallowequal` and `warning` dependencies

### ISSUE THREAD

**Issue by andykenward** [nfl/react-helmet#198]
Just going through the dependencies and dont see `shallowequal` or `warning` being used anywhere. 

Would it be safe to remove these?

https://github.com/nfl/react-helmet/blob/f0b971c467ab9854b47b5f7c808f8da464fb1ccc/package.json#L33-L34

**Comment by cwelch5** [comment]
I think you are right.  Must have been artifacts from before.
