### ISSUE TITLE
htmlAttributes with className doesn't work with isomorphic applications

### ISSUE THREAD

**Issue by koenpunt** [nfl/react-helmet#204]
When adding `className` to `htmlAttributes` it works correct on the server, but the client adds a new `classname` attribute to the html element. And when using `class`, the server can't apply the class correctly.

**Comment by coreyleelarson** [comment]
Why was this closed? I am having the exact same problem with the latest version of react-helmet.

**Comment by koenpunt** [comment]
See #205
