### ISSUE TITLE
Npm install issue: Cannot read property 'babel' of undefined

### ISSUE THREAD

**Issue by michaelBenin** [nfl/react-helmet#207]
Admins-MacBook-Pro-3:react-ssr-spa mbenin$ npm i react-helmet --save --save-exact
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/mbenin/.nvm/versions/node/v6.9.1/bin/node" "/Users/mbenin/.nvm/versions/node/v6.9.1/bin/npm" "i" "react-helmet" "--save" "--save-exact"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8

npm ERR! Cannot read property 'babel' of undefined

**Comment by michaelBenin** [comment]
Issue was in my shrinkwrap.

**Comment by tacnoman** [comment]
Thanks @worc :D
