### ISSUE TITLE
Example with dynamic meta tag would be helpful

### ISSUE THREAD

**Issue by richardsondx** [nfl/react-helmet#214]
Issue:
http://stackoverflow.com/questions/41061233/issue-with-loading-dynamic-meta-tag-value-in-react-app-using-server-side-renderi?noredirect=1#comment69495327_41061233

**Comment by potench** [comment]
This is not an issue with react-helmet, but with fetching data before calling `React.renderToString()` on the server. http://stackoverflow.com/questions/30974007/fetching-data-before-rendering-server-side
