### ISSUE TITLE
no support for react 0.14

### ISSUE THREAD

**Issue by giogonzo** [nfl/react-helmet#226]
Hi there, with [this commit](https://github.com/nfl/react-helmet/commit/042b38db37e50008b82a2ee17f5cc9a9d5900813) support for react 0.14 is gone (see e.g. https://github.com/facebook/react/issues/5355)

Which is fine, but not if released as a "patch" version I'd say? 😇 

Also I don't see any `peerDependencies` on react >= 15, is this deliberate?

**Comment by cwelch5** [comment]
Thanks @giogonzo for looking out.  I reverted just the NullComponent portion and tested with React 0.14.8.  I marked 3.3.1 as broken and bumped to 3.3.2.  I kept peerDependencies omitted for now.  I will add back in a future release.

**Comment by cwelch5** [comment]
Published Helmet v4.0.0 with a requirement for React 15.  Thanks.

**Comment by giogonzo** [comment]
Thank you for the fast turnaround
