### ISSUE TITLE
Usage of class in htmlAttributes with 3rd party classes.

### ISSUE THREAD

**Issue by coreyleelarson** [nfl/react-helmet#232]
## Step 1: Server Renders App
I have an isomorphic react application. I am using trying to use htmlAttributes to set the class for each section of the app. I have an Html component which gets rendered only on the server-side, and I'm using *Helmet.rewind()* to inject the head section. This all works flawlessly.

**App.js**
```jsx
...
render() {
  return (
    ...
    <Helmet htmlAttributes={{ lang: 'en', class: 'layout-app' }} titleTemplate="%s | DomainName.org" />
    ...
  );
}
...
```

**Html.js (only rendered server-side)**
```jsx
...
render() {
  const head = Helmet.rewind();
  return (
    ...
    <html {...head.htmlAttributes}>
    ...
  )
}
...
```

**Server-Rendered App Html**
```html
<html data-reactroot="" data-reactid="1" data-react-checksum="2014671351" class="layout-app" lang="en" data-react-helmet="lang,class">
```

## Step 2: Typekit Initializes

I also am using Typekit, which injects its own classes into the HTML tag client-side.

**Typekit-initialized Rendered Html**
```html
<html data-reactroot="" data-reactid="1" data-react-checksum="2014671351" class="layout-app wf-lato-i4-active wf-lato-i7-active wf-lato-n7-active wf-lato-n4-active wf-keplerstdsemicondenseddis-n7-active wf-keplerstdsemicondenseddis-i7-active wf-active" lang="en" data-react-helmet="lang,class">
```

## Step 3: Client Routes To Admin
The problem I'm having is when I route client-side to a different part of the application, which has a different HTML class, it removes all of the Typekit-specific classes.

**Admin.js**
```jsx
...
render() {
  return (
    ...
    <Helmet htmlAttributes={{ lang: 'en', class: 'layout-admin' }} titleTemplate="Admin %s | DomainName.org" />
    ...
  );
}
...
```

**Client-Rendered Admin Html**
```html
<html data-reactroot="" data-reactid="1" data-react-checksum="2014671351" lang="en" class="layout-admin" data-react-helmet="lang,class">
```

Am I doing something wrong with the setup or is there anything I can do to bypass this issue?

**Comment by coreyleelarson** [comment]
Nevermind, I need to do more analysis. The first section was not actually working correctly.

**Comment by thejamespower** [comment]
@coreyleelarson how did you get this to work? I'm having a similar issue with using `<html className='...` that is overriding all other applied classes.

**Comment by coreyleelarson** [comment]
@thejamespower I went a different route, so I don't think I ever got it working. Sorry. :(
