### ISSUE TITLE
No `render` method found

### ISSUE THREAD

**Issue by raymestalez** [nfl/react-helmet#241]
I am trying to use this component as described in README, but getting the following errors:

    bundle.js:2310Warning: NullComponent(...): No `render` method found on the returned component instance: you may have forgotten to define `render`, returned null/false from a stateless component, or tried to render an element whose type is a function that isn't a React component.

    Uncaught TypeError: inst.render is not a function

Am I doing something wrong? Can you help me out?

My code:

```
import Helmet from "react-helmet";

....

and then, in component:

    render() {
	return (
	    <header>
		<Helmet title="My title" />
	    </header>
	);
    }
```

**Comment by cwelch5** [comment]
I'm guessing the `returned null/false from a stateless component` part of the warning is the problem.  Helmet does return null from a stateless component, which requires React 15.  Can you make sure you are using React 15+?  I'll make sure to make this more obvious in the README.
