### ISSUE TITLE
How to handle https reverse proxy and resources

### ISSUE THREAD

**Issue by kopax** [nfl/react-helmet#242]
I have this error when I deploy my app to production : 

    webpack:///./~/react-helmet/lib/Helmet.js?:259 Mixed Content: The page at 'https://dev-app.domain.com/playground' was loaded over HTTPS, but requested an insecure stylesheet 'http://haltalk.herokuapp.com/explorer/vendor/css/bootstrap.css'. 
    This request has been blocked; the content must be served over HTTPS.

I could simply use https to access heroku, that would work. But after I will download resources over https in development while I don't need.

What is the appropriate approach ?

**Comment by doctyper** [comment]
This is outside the scope of this project. Helmet itself is protocol-agnostic, it is up to the developer to request resources using the appropriate protocol.

I would suggest researching [protocol-relative urls](https://jeremywagner.me/blog/stop-using-the-protocol-relative-url) and choosing the best technique that fits your needs.
