### ISSUE TITLE
dist-tags on npm incorrect, showing 5.0.0-beta as latest

### ISSUE THREAD

**Issue by lourd** [nfl/react-helmet#245]
I'm updating my dependencies with the `yarn upgrade-interactive` tool and it's reporting that 5.0.0-beta is the latest version for react-helmet.

<img width="770" alt="screen shot 2017-03-16 at 12 03 10 pm" src="https://cloud.githubusercontent.com/assets/2012388/24005855/8f13c582-0a40-11e7-8709-45385fc55cc1.png">

Doesn't look like that's an actual release or tag on Github, but I am seeing that [on npm](https://www.npmjs.com/package/react-helmet). Running `yarn info react-helmet` (or `npm show react-helmet`) I'm seeing that the `'dist-tags'` are `latest: '5.0.0-beta'` and `next: '2.0.0'`.

Seems like `latest` should be `4.0.0` and `next` (if it exists) should be `5.0.0-beta`

**Comment by doctyper** [comment]
Thanks! I just fixed this. `latest` now points to `4.0.0`.

**Comment by lourd** [comment]
Nice! Thanks for your quick response and action
