### ISSUE TITLE
Not Working in ServerSide Rendering 

### ISSUE THREAD

**Issue by zeeshanjan82** [nfl/react-helmet#247]
I am facing an issue with using the library. I am using the seed project : https://github.com/reactGo/reactGo Actually my requirement is to show the preview of the blog post along with the preview image to the user when sharing the blog post in facebook or twitter. I need to set the og:title and other related tags for this and I need to do all this dynamically as my blog titles will change and the same page will render all the different blogs with different titles. I am using this seed project which supports serverside rendering. When I keep the static string values in title on this page: https://github.com/reactGo/reactGo/blob/master/app/pages/Vote.jsx   then I can see the title being applied also when I do 'view source' I see that title but when I keep the dynamic title pulling it from the store/state I can see the title applied when I do 'inspect element' also on the title of browser window but when I do a 'view source' of the page the title is not set and restores to default. Without this I am not able t to share the blog posts on facebook as it picks the default title and not the ones I set.

**Comment by cwelch5** [comment]
In `reactGo` you'll need to do a `Helmet.rewind()` where the tags are set for the server-side render.  Refer to the README for details.

**Comment by zeeshanjan82** [comment]
Hi @cwelch5 actually I am using a seed project 'reactGo' which already uses Helmet.rewind() I don't think the problem is with Helmet library as it changes the title and the meta tags and I can see them changed when I 'inspect element' I have gone with other approach for now so can close this ticket.

**Comment by vsc-github** [comment]
@cwelch5 `ReactGo` is using `helmet.rewind` but it seems like the meta tags get updated after the first render which is why facebook doesnt pick the `og:tags`. Any workaround to that?

**Comment by garmjs** [comment]
In latest version v5 on server-side `Helmet.renderStatic()` aliased to `Helmet.rewind()` for more clarity. rewind will be **deprecated** in the future.
