### ISSUE TITLE
Mounting Helmet Tests not working in v5

### ISSUE THREAD

**Issue by tomatau** [nfl/react-helmet#260]
Running tests for document.head updates using enzyme's `mount` function for version 4 and all works fine. Started a migration to v5 but my mounted tests have stopped working.

Setup document:
```js
import { jsdom } from 'jsdom'
import { keys } from 'ramda'

global.document = jsdom(
  '<html><head></head><body><div id="application-root"></div></body></html>'
)
global.window = document.defaultView
keys(document.defaultView).forEach(property => {
  if (typeof global[property] === 'undefined') {
    global[property] = document.defaultView[property]
  }
})

global.navigator = { userAgent: 'node.js' }
```

My main application render:
```js
const Main = () =>
        <DocumentMeta
          defaultTitle='Breko Hub'
          titleTemplate='%s | Breko Hub'>
          <html lang='en' />
          <meta charSet='utf-8' />
        </DocumentMeta>
```

Running the tests
```js
const wrapper = mount(Main, { attachTo: document.getElementById('application-root') })

setImmediate(() => {
  // This works:
  expect(document.title).to.eql('Breko Hub')

  // This doesn't work anymore in v5, worked fine in v4
  const meta = document.querySelector('meta')
  // meta === null
})
```

I have server side tests ensuring that the server renders the appropriate attributes and they work fine using `Helmet.canUseDOM = false`. But the client-side tests which actually assume the DOM is usable, aren't working anymore. The document.head remains empty.

```js
const wrapper = mount(Main, { attachTo: document.getElementById('application-root') })

setImmediate(() => {
  (document.head || document.querySelector('head')).innerHTML
  // returns an empty string
})
```

**Comment by doctyper** [comment]
Helmet 5 batches DOM updates via [`requestIdeCallback`](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback). It is now possible to query the DOM before Helmet performs its update.

[Take a look at our tests](https://github.com/nfl/react-helmet/blob/master/test/HelmetDeclarativeTest.js#L49-L70) to see how we've dealt with this change.

**Comment by tomatau** [comment]
@doctyper I did look at your tests and saw you run them in Karma. `requestIdleCallback` doesn't exist in a JSDOM, a setImmediate works though.

**Comment by doctyper** [comment]
You can use [our polyfill](https://github.com/nfl/react-helmet/blob/master/test/HelmetDeclarativeTest.js#L10):

```js
import {requestIdleCallback} from "react-helmet/src/HelmetUtils";
```

**Comment by tomatau** [comment]
Thanks, should be fine, it's just a setTimeout, I'm happy with a setImmediate and less coupling ;)

**Comment by coreyleelarson** [comment]
@doctyper Thank you for that! Though, I was only able to import it from lib:
```javascript
import { requestIdleCallback } from 'react-helmet/lib/HelmetUtils';
```

**Comment by joselcc** [comment]
I looks like **requestIdleCallback** [was replaces](https://github.com/nfl/react-helmet/commit/a2323add50c15bf6a1047b5d99753cce6db07fd6) with **requestAnimationFrame** from v5.2.0

you will need to import it instead
```js
import { requestAnimationFrame } from 'react-helmet/lib/HelmetUtils'; 
.....
.........
describe('Something', () => {
  it('set title', done => {
    ReactDOM.render(
      <Helmet defaultTitle={'Fallback'} title={'Test Title'} />,
      container
    );

    requestAnimationFrame(() => {
      expect(document.title).toEqual('Test Title');
      done();
    });
  });
});
```
