### ISSUE TITLE
Usage with react-intl

### ISSUE THREAD

**Issue by smashercosmo** [nfl/react-helmet#268]
I suggest, that this should be allowed
```jsx
<Helmet >
   <FormattedMessage {...msg.title}>
      {title => <title>{title}</title>}
   </FormattedMessage>
</Helmet>
```
What do you think?

**Comment by cwelch5** [comment]
Thanks for your interest in Helmet.

You can see an explanation here - https://github.com/nfl/react-helmet/issues/262#issuecomment-291000077

**Comment by cesarp** [comment]
You can also use the `injectIntl` HoC and do `intl.formatMessage()` in your component instead.

**Comment by smashercosmo** [comment]
@cesarp Yes, I know that. I just prefer less imperative approach.

**Comment by smashercosmo** [comment]
@cwelch5 By the way, just FYI https://twitter.com/dan_abramov/status/855872355406671872 ))

**Comment by fxlemire** [comment]
You can simply switch things around:

```
<FormattedMessage id="msg.title">
  {title => <Helmet><title>{title}</title></Helmet>}
</FormattedMessage>
```

**Comment by fadlikadnmitrais** [comment]
> You can simply switch things around:
> 
> ```js-jsx
> <FormattedMessage id="msg.title">
>   {title => <Helmet><title>{title}</title></Helmet>}
> </FormattedMessage>
> ```

Thanks @fxlemire , it works!

**Comment by Qnedy** [comment]
> You can simply switch things around:
> 
> ```js-jsx
> <FormattedMessage id="msg.title">
>   {title => <Helmet><title>{title}</title></Helmet>}
> </FormattedMessage>
> ```

save my day! kkk
