### ISSUE TITLE
Conditional comments?

### ISSUE THREAD

**Issue by iamdustan** [nfl/react-helmet#270]
:wave: did a quick search and didn’t see a mention to whether this supports rendering comments in the `<head />` tag (arbitrary comments or IE conditional comments).

:v:

**Comment by doctyper** [comment]
No @iamdustan, Helmet does not currently support rendering comments.

**Comment by iamdustan** [comment]
:thumbsup: thanks for the quick rersponse @doctyper. Is that a goal or desire at all?

**Comment by zheeeng** [comment]
Have the same question

**Comment by tiagonapoli** [comment]
Have the same question too
