### ISSUE TITLE
react-helmet causes PropTypes warning on React 15.5.X and later

### ISSUE THREAD

**Issue by fortinmike** [nfl/react-helmet#273]
When migrating to React 15.5.X, react-helmet causes a warning to be emitted:

    Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Details here: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

**Comment by bmv437** [comment]
Which version of react-helmet are you using?
looks like the latest version [5.0.3](https://github.com/nfl/react-helmet/compare/5.0.2...5.0.3) addresses that issue. See this [PR](https://github.com/nfl/react-helmet/pull/265).

**Comment by fortinmike** [comment]
Ok, I was using a massively outdated version it seems. I assumed my IDE presented me with the latest and greatest. My bad.

**Comment by Pomax** [comment]
I'm currently seeing the exact same warning using react-helmet 5.2.0 with React 15.2
