### ISSUE TITLE
Replace shallowequal with deep-equal

### ISSUE THREAD

**Issue by gajus** [nfl/react-helmet#284]
@dashed just released a v1 of https://github.com/dashed/shallowequal which (among other improvements) removes the dependency on lodash.

Despite being a major version update, it does not have breaking API changes. Therefore, an update simply requires to bump the version in package.json and release a patch.

**Comment by dashed** [comment]
hmm... it seems deep-equal is being used in favour of shallowequal: https://github.com/nfl/react-helmet/pull/200

v3.2.2 still has it: https://github.com/nfl/react-helmet/blob/3.2.2/package.json

but v3.2.3 does not: https://github.com/nfl/react-helmet/blob/3.2.3/package.json

**Comment by gajus** [comment]
Oops. Opened an issue with a wrong repository. This was meant to be opened with https://github.com/gaearon/react-side-effect. `react-helmet` uses `react-side-effect`, `react-side-effect` uses `shallowequal`.

https://github.com/gaearon/react-side-effect/issues/35

**Comment by gajus** [comment]
That said, `react-helmet` could replace `deep-equal` with `shallowequal` to reduce the dependency tree.

**Comment by magalhas** [comment]
@gajus apparently shallowequal latest release is breaking webpack production builds (uglify does not support let statements yet).

**Comment by bradyhigginbotham** [comment]
Just ran into this same issue with shallowequal and Uglify.

**Comment by cwelch5** [comment]
@gajus I believe we used `deep-equal` because with children the object comparison in `shouldComponentUpdate` was always false, even if the children were unchanged.  We needed a way to truly check equality between children in props.

**Comment by bradyhigginbotham** [comment]
@cwelch5 Version of shallowequal has been pushed with the Uglify fix.

**Comment by jcreamer898** [comment]
https://github.com/gaearon/react-side-effect/issues/36

**Comment by gimdongwoo** [comment]
It's not react-helmet's responsiblity.

The {{react-side-effect}} was released from 1.1.0 to 1.1.1, changing {{shallowequal}} from 0.2.2 to 1.0.0.
