### ISSUE TITLE
Meta description disappears when changing the page

### ISSUE THREAD

**Issue by bloodymind** [nfl/react-helmet#290]
Dear all,

I have a weird issue! i can perfectly display my `meta description` and `title` when reloading my pages. but only `meta description` disappears when changing the page, i have to refresh the page to see its result!

When the page is loaded :
```
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Page title | website.com</title>
  <meta data-react-helmet="true" name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <meta data-react-helmet="true" name="description" content="Website description">
```
When clicking on any link in the website and get back to this page :
```
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Page title | website.com</title>
  <meta data-react-helmet="true" name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
```

*Ps*: i've tried both helmet format and still get the same result :
```
return (
      <Helmet>
        <title>{ title }</title>
        <meta name="description" content={ description } />
      </Helmet>
    );
```
And 
```
return (
      <Helmet
        title={ metaTitle }
        meta={[{ name: 'description', content: metaDescription }]}
      />
    );
```
Any idea about that please ?

**Comment by GazzaHazza** [comment]
I am also having this issue. Anyone had any luck with fixing or knowing why?

**Comment by bloodymind** [comment]
@GazzaHazza just check well DOM you will find it, it was really stupid from me :/ 

Otherwise please share your screen and code to see what is the issue.
