### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by parkeragee** [nfl/react-helmet#292]
When I try adding script tags, they show up in the HTML (inspect page source) just fine, but the Javascript code does not get initiated and therefore I get errors in the console.
<img width="643" alt="screen shot 2017-06-15 at 3 33 25 pm" src="https://user-images.githubusercontent.com/4029349/27200620-0ccfd1aa-51e0-11e7-9e11-26f304149e92.png">

**Comment by alepee** [comment]
you're trying to add jquery-ui before `jQuery` or `$` object to be added to `window`. Maybe you forgot to include jQuery to your app, or you may have jquery-ui append before jquery by react-helmet.
