### ISSUE TITLE
Cannot find module "he"

### ISSUE THREAD

**Issue by zimok** [nfl/react-helmet#3]
Just installed via npm, required it in a React component and when launch server I got this:

    ERROR in ./~/react-helmet/dist/Helmet.js
    Module not found: Error: Cannot resolve module 'he'

Using npm 2.7.0

**Comment by zimok** [comment]
I Think you should move "he" from devDependencies to dependencies in package.json.
Let me know if I can help.
tnx

**Comment by choonkending** [comment]
:+1:

**Comment by sugarshin** [comment]
:+1:
