### ISSUE TITLE
Why the project uses peerDependencies section? 

### ISSUE THREAD

**Issue by olebedev** [nfl/react-helmet#30]
Actually, I need it in React 0.12.2, but installation failed.
Does project use some react >=0.13 specific features in runtime? It looks like react >=0.13 need only for ES6 is isn't it?

Thanks!

**Comment by cwelch5** [comment]
We will look into dropping the peerDependency; I know we were running into issues with including React.

**Comment by cwelch5** [comment]
@olebedev We've dropped the peer dependency.  You can check out our latest release - 2.1.0.

**Comment by olebedev** [comment]
👍
