### ISSUE TITLE
How to control order or meta tags?

### ISSUE THREAD

**Issue by jamesladd** [nfl/react-helmet#311]
Is the a way to control the order of meta tags added with react-helmet?
For example bootstrap requires jQuery to be loaded before it but there is not predictable order from
react-helmet - as far as I can see.

**Comment by tmbtech** [comment]
This issue is over a year old. Closing, but feel free to reopen if needed.

**Comment by felipe-kosouski** [comment]
Is there a solution to this? I need to add a external script via react helmet and this scripts needs to load first, right after the head tag opens

**Comment by andrewslock** [comment]
Did someone resolved it yet?
