### ISSUE TITLE
Initial Page Load issues - Head not updated until after load.

### ISSUE THREAD

**Issue by aequasi** [nfl/react-helmet#314]
Working with an issue right now, trying to get the head to update as soon as possible, as my page loads data over time and shows a loading div until its done.

Throughout the request though, enough data is populated early to update the head. However, even if i render different data in `<Helmet {...this.meta()} />`, none of it is rendered/updated in the dom until AFTER the page is fully loaded. 

Is there a way around this, besides SSR?

**Comment by cwelch5** [comment]
@aequasi We just released a `defer` prop that you can set to `false` which will not use `requestAnimationFrame` and instead will update the DOM as soon as possible.  If you want data to show up even earlier, make sure to put your most important data as high up in your component tree as possible.

**Comment by aequasi** [comment]
Awesome! That worked.

closed by #297

**Comment by mrlaseptima** [comment]
hi.
@cwelch5 thank you. defer={false} work for me .

**Comment by mzulfanw** [comment]
i'm faced issue when i added defer={false}, when i'm reload apps, the current show its still from the index.html, can anyone help me about this, thanks before
