### ISSUE TITLE
Apple Smart Banner not working

### ISSUE THREAD

**Issue by jayasme** [nfl/react-helmet#319]
Hi

I am using the library for setting the title & meta that makes my webpage prompting Apple's smart banner on iOS platform. But I found that it not working for me, I've tried do the following:

```javascript
...
if (isIOS(window.navigator.userAgent)) {
    return (
      <Helmet
        meta={[
          {
            name: 'apple-itunes-app',
            content: `app-id=${appStoreId}, app-argument=${deepLink}`,
          },
        ]}
      />
    );
  }
...
```

and the HTML code looks no problem like the following screenshot

<img width="916" alt="1" src="https://user-images.githubusercontent.com/668198/30803940-2378b172-a21e-11e7-95cd-4a72579cfcad.png">

I am confused by the situation for about 2 days, I've tried to add the meta to raw HTML files it ran perfectly, buy in React code it not working anymore and I googled the problem no one can answer my question, so anyone in here has solution for my problem or it's really an issue in the library?

Thanks

**Comment by jayasme** [comment]
I found that the meta info is not rendered at the page first loading, it rendered after a while with async methods of React, so I think this is the key why Safari can't recognize the meta.

**Comment by judyn** [comment]
Also having this issue, any help is appreciated!

**Comment by potench** [comment]
Yep, you need to server-side render your web app for the metadata/title managed by react-helmet to be rendered as part of the script source.  Once you're rendering your React app on a server you can checkout how to render react-helmet on the server here: https://github.com/nfl/react-helmet#server-usage
