### ISSUE TITLE
Release of patch version for 0.14.0-beta React versions

### ISSUE THREAD

**Issue by romanenko** [nfl/react-helmet#33]
Hello. Thanks for the great lib! It is a great improvement over original `<DocumentTitle />`.

I'm trying to install it it an App with React 0.14.0-beta3 and I see a fix f9320ce5b1c26e191867dd08f329603fe5b343fd But I can't use this version because if i specify

    ...
    "react-helmet": "nfl/react-helmet",
    ...

then I get `Module not found: Error: Cannot resolve module 'react-helmet' in ...`, I suppose, because `dist` folder is missing in the repository.

So, please, could you build and publish this fixed version to npm? Or, even better, it would be great if there will be no `peerDependencies` section at all #30

**Comment by cwelch5** [comment]
Yep, we just merged in the fix last night and we will be publishing.  Thanks.

**Comment by cwelch5** [comment]
Published v 1.1.2.  Thanks.
