### ISSUE TITLE
Script type="application/ld+json" do not produce any output

### ISSUE THREAD

**Issue by umbobabo** [nfl/react-helmet#330]
From the readme this...
```
<Helmet>
      <script type="application/ld+json">{`
         {
             "@context": "http://schema.org"
         }
     `}</script>
    </Helmet>
```
should be a supported script but it doesn't seem to produce any output.
Reading the test [here](https://github.com/nfl/react-helmet/blob/86276f3bd13ecbffd25d7ef68a9c019fdd07cffa/test/HelmetTest.js#L1904) it seems that tags without src are not accepted, and this obviously could be the root cause of the issue.

**Comment by umbobabo** [comment]
Close this cause the problem is not present in the latest version.

**Comment by VincentCtr** [comment]
It seems that I have the issue on the latest version. (5.2.0) Any idea of what happen ?

**Comment by VincentCtr** [comment]
Oups.. seems that I forgot
`{helmet.script.toComponent()}
`
