### ISSUE TITLE
Not working on IE11 after upgrading to v5

### ISSUE THREAD

**Issue by satazor** [nfl/react-helmet#336]
react-helmet@5 uses `requestAnimationFrame` which IE 11 supports but has a weird bug in strict mode (which is turned on automatically when you use es6 modules).

Basically it must be either called with `window` context or bound to it or it will throw with `Invalid calling object`. See this thread that describes the same bug in vuejs: https://github.com/vuejs/vue/issues/4465 and also their fix to it: https://github.com/ant-design/ant-design/commit/0a9a3887b5bc7d87f3f509f3d28dc2b1ce698408#diff-3537c7c5164da1c7f03e6eed0346218fR20.

**Comment by Kernle32DLL** [comment]
One could probably use https://github.com/nfl/react-helmet/issues/314 as a workaround till this issue is fixed properly.

**Comment by satazor** [comment]
@Kernle32DLL apparently I need to set `defer` to false in all places that I use <Helmet>. Is there a defaultDefer?

**Comment by satazor** [comment]
@Kernle32DLL ended up doing this:

```
// Force default defer to `false` until Helmet works out a bug on IE11
// See: https://github.com/nfl/react-helmet/issues/336
Helmet.defaultProps.defer = false;
```

Hacky, but works for now.
