### ISSUE TITLE
Example universal app

### ISSUE THREAD

**Issue by mattdennewitz** [nfl/react-helmet#34]
Not really an issue per se, but I'm unsure of where to file this (short of sending a presumptuous PR). I've put together a no-frills, easy to understand example of a universal app using `react-helmet` with `react` and `react-router`. I'd like to suggest its inclusion in the docs.

- `react-helmet-example`: https://github.com/mattdennewitz/react-helmet-example. 

Thanks!

**Comment by cwelch5** [comment]
This is great, thanks!  I'd like to see some of the more advanced usage (like nesting and duplicate tags in the same component).  The app is very easy to follow.

**Comment by mattdennewitz** [comment]
@cwelch5 Great! I've added nested routes. Take a look!

**Comment by cwelch5** [comment]
Thanks for the great examples.  We got a link added to the README in 1.1.3
