### ISSUE TITLE
Helmet renders empty title on server

### ISSUE THREAD

**Issue by ImanMh** [nfl/react-helmet#343]
I have this code in my component: 
```
<Helmet>
    <title>My Title</title>
    <link rel="canonical" href="http://mysite.com/example" />
</Helmet>
```

I also have this in my server.js
```
const html = ReactDOM.renderToStaticMarkup(<Html {...data} />);
```

And finally my Html.js
```
const helmet = Helmet.renderStatic();
console.log(helmet.title.toString());
```

This should outputs:
```
<title>My Title</title>
```
but instead I get this: 
```
<title data-react-helmet="true"></title>
```

What is your guess about this issue?

**Comment by ImanMh** [comment]
This was totally my fault and it was caused by putting 
```
<Helmet>
    <title>My Title</title>
    <link rel="canonical" href="http://mysite.com/example" />
</Helmet>
```

where it was not rendered in server. (in my loading component)

**Comment by Mixpeal** [comment]
i just got out of this problem, this is the fix, make sure 

`const helmet = Helmet.renderStatic(); `

is called after

`ReactDOMServer.renderToString(<Handler />);`
