### ISSUE TITLE
Dynamic update title when tab not selected

### ISSUE THREAD

**Issue by chacbumbum** [nfl/react-helmet#350]
Hi everyone. I want title auto update like facebook when notification

This is my code:
```javascript
<Helmet titleTemplate={`${total > 0 ? `(${total})` : ''} Page - %s`} />
```
But it does not work when the browser tab is not selected.

**Comment by pedi** [comment]
I encountered a similar issue and dig into the code.
The cause is due to following code

```javascript
const handleClientStateChange = newState => {
    if (_helmetCallback) {
        cancelAnimationFrame(_helmetCallback);
    }

    if (newState.defer) {
        _helmetCallback = requestAnimationFrame(() => {
            commitTagChanges(newState, () => {
                _helmetCallback = null;
            });
        });
    } else {
        commitTagChanges(newState);
        _helmetCallback = null;
    }
};
```

The `requestAnimiationFrame` callback will not be called if browser tab is in active. 

I think it's better add a timeout as fallback.

**Comment by pedi** [comment]
so the solution would be to set `defer` in the helmet props.

https://github.com/nfl/react-helmet/commit/b22e2f4075971f8b80568cd9911a2143f602add1

I suggest you upgrade your lib version and close this one

**Comment by chacbumbum** [comment]
I'm using version 5.2.0 and this is my code:
```js
<Helmet defer titleTemplate={`${total > 0 ? `(${total})` : ''} Page - %s`} />
```
and it still does not work

**Comment by rajatvijay** [comment]
Hey @pedi, @chacbumbum did you find any solution to this problem?

defer is not working in my case too.

I am trying to show a count-up timer in the page's title using `setState` but the timer seems to not render the new title when the tab is not visible/selected/focused. 

Would love to get a solution for it. Thanks in advance.

**Comment by ayushikhetan** [comment]
<Helmet defer={false} titleTemplate={`${total > 0 ? `(${total})` : ''} Page - %s`} /> will work

**Comment by chacbumbum** [comment]
@rajatvijay I was clone repo into to my workspaces

I change code from `src/HelmetUtils.js`

```javascript
const handleClientStateChange = newState => {
    if (_helmetCallback) {
        cancelAnimationFrame(_helmetCallback);
    }

    if (newState.defer) {
        _helmetCallback = requestAnimationFrame(() => {
            commitTagChanges(newState, () => {
                _helmetCallback = null;
            });
        });
    } else {
        commitTagChanges(newState);
        _helmetCallback = null;
    }
};
```
to
```javascript
const handleClientStateChange = newState => {
    if (_helmetCallback) {
        cancelAnimationFrame(_helmetCallback);
    }

    if (newState.defer) {
        _helmetCallback = setTimeout(() => {
            commitTagChanges(newState, () => {
                _helmetCallback = null;
            });
        }, 100);
    } else {
        commitTagChanges(newState);
        _helmetCallback = null;
    }
};
```

**Comment by rajatvijay** [comment]
@ayushikhetan 

> <Helmet defer={false} titleTemplate={${total > 0 ?(${total}): ''} Page - %s} /> will work

this worked for me. Thanks!

**Comment by chacbumbum** [comment]
@ayushikhetan althought it not work for me :( but i will close this issue.
