### ISSUE TITLE
Remove script previously added

### ISSUE THREAD

**Issue by qbitza** [nfl/react-helmet#352]
Hi guys,

I hope this is a FAQ, and I'm just not finding the answer.

We have a situation where we need to add a script on a specific page and every time the user visits that page the script should trigger again. Currently it triggers once, the first time, and then the script tag stays in the head. It is never removed, and hence never added again and therefore never fires again.

How do I remove or clear all scripts at the App level, to ensure only the required scripts are added when they're needed?

**Comment by adomrockie** [comment]
I am in the same boat. anybody knows how to?

**Comment by jamsea** [comment]
@qbitza I'm not entirely sure what the issue is. Could you listen to `document.onload` or another event (mouse click somewhere, etc) to trigger it?

**Comment by vidjuheffex** [comment]
@qbitza this is definitely not the way to approach this. Loading and calling scripts are two separate things. Check how the script is invoked (not loaded) the first time and work from there.

**Comment by qbitza** [comment]
@vidjuheffex Thanks, that's the route I took.

**Comment by himanshu309** [comment]
I have somewhat similar issue but in my case the scripts are adding again and again ...Any Help ??
