### ISSUE TITLE
Support of boolean attributes

### ISSUE THREAD

**Issue by lgordey** [nfl/react-helmet#366]
I'm making [AMP](https://www.ampproject.org/docs/) version of site and try to do this:
```jsx
<Helmet>
  <style amp-custom>
    {myCustomStyles}
  </style>
<Helmet>
```
Output:
```html
<style data-react-helmet="true" amp-custom="true">
  <!-- myCustomStyles -->
</style>
```
Error:
`The attribute 'amp-custom' in tag 'style amp-custom' is set to the invalid value 'true'`

**So the question:** 
Is there a way to prevent boolean attributes transform to `=true`?

**_P.S._** Works the same with `<script async>` and etc.

**Comment by doctyper** [comment]
Yes, just use `amp: undefined` And it should render without a value.

**Comment by lgordey** [comment]
@doctyper Thanks man 👍
