### ISSUE TITLE
Canonical link not appearing in head server side rendering

### ISSUE THREAD

**Issue by ronfogel** [nfl/react-helmet#370]
using the following code
```
<Helmet>
        <title>test</title>
        <link rel="canonical" href="http://mysite.com/example" />
      </Helmet>
```

returning only the title in server side rendering while in client side rendering it works.

**Comment by intelcoder** [comment]
I have same issue! Meta and title tags are rendered but not link

**Comment by intelcoder** [comment]
canonical link shows on client side. I feel canonical get overwritten by stylesheet link

**Comment by aconital** [comment]
Having the same issue, not showing on server side

**Comment by ronfogel** [comment]
it did the trick. thank you very much!
