### ISSUE TITLE
link tags should not be closed

### ISSUE THREAD

**Issue by igoldny** [nfl/react-helmet#385]
Hey,

I noticed that link tags rendered with helmet are self-closed with a slash at the end like all valid HTML tags should be but apparently, they should leave open.
 
when the browser reads those tags he automatically fixes those tags and removes slash from them which create inconsistency between server and client which according to google "SEO experts" might affect somehow on what google reads...

for example canonical link tag looks like this:

### current behavior:
server:
```
<link rel="canonical" href="url" />
```
client:
```
<link rel="canonical" href="url">
```

### expected behavior:
server:
```
<link rel="canonical" href="url">
```
client:
```
<link rel="canonical" href="url">
```

**Comment by winfredkqin** [comment]
Both formats are valid syntax. Google is smart to handle such things.
