### ISSUE TITLE
Meta tag load after page load 

### ISSUE THREAD

**Issue by Pratiktarade** [nfl/react-helmet#387]
Hi I am using Next js for server side rendering but all thing working fine but  when mobile device need view port  i trying   Meta, as well as Helmet , react-meta-tags,  but  meta tag load after page load 2.3 second,
Url : www.weswap.io

  render() {
    return (

      <Head>
   <title>weswapio</title>
   <meta charSet='utf-8' />
   <meta name="description" content="That's it!" />
   <meta name='viewport'content='width=device-width, initial-scale=1.0' />
   <div className="header-wrapper">
      <Row>
      <Col lg="12" md="12" sm="12">
        <header className="header">
          <Menu body={<div />} />
        </header>
        </Col>
        </Row>
      </div>
        </Head>
    );
  }
please help me .. Thanks

**Comment by Asday** [comment]
Please see [this section](https://github.com/nfl/react-helmet#server-usage) in the README.  When rendering on the server, you'll need to call `Helmet.renderStatic()` to retrieve the final `<head />` tags output, then inject those into `<head />` from within Next as detailed in [their README](https://github.com/zeit/next.js#populating-head).
