### ISSUE TITLE
This project is still alive?

### ISSUE THREAD

**Issue by rroslaniec** [nfl/react-helmet#391]
I'm worried about Helmet is abandoned...

**Comment by Asday** [comment]
I had a glance through some of the open issues and they all seem to be "how do I do this?" style stuff much better suited to StackOverflow.

Helmet has no vulnerabilities reported on npm.

I don't see a reason for there to be any active maintenance at this stage.

**Comment by davalapar** [comment]
An alternative:

https://open.nytimes.com/the-future-of-meta-tag-management-for-modern-react-development-ec26a7dc9183

https://github.com/staylor/react-helmet-async

**Comment by Asday** [comment]
I still don't see a reason to not use this project, @davalapar.  Helmet works absolutely fine for what it needs to do - there's nothing wrong with it.

**Comment by davalapar** [comment]
Yeh nothing really wrong here mate, those links are just other people working on minor things not addressed by this project.

**Comment by AubreyHewes** [comment]
@Asday Active maintenance is one thing. Resolving/Closing issues and or PRs is a sign of activity .. this project gives a sniff of abandoned. 

I also mailed the nfl, hopefully they will call to arms for the community to help.

**Comment by Asday** [comment]
@AubreyHewes At the risk of becoming a broken record: there are no issues that I found with a quick hunt that actually _are_ issues.  If the difference between the author clicking "close" and not clicking "close" is enough to make you hunt for an alternative then I don't know what I can tell you.

**Comment by AubreyHewes** [comment]
@asday Resolving/Closing issues and or PRs are signs of activity. No signs is a sign of abandonment.

I do not understand your reaction. Are you a maintainer? I also did not say that I was looking for an alternative.. a little project maintenance maybe.

If any one _is_ a maintainer look at 

https://github.com/nfl/react-helmet/pull/397 a major issue as the current strategy is broken, https://github.com/nfl/react-helmet/pull/400

x

**Comment by corydeppen** [comment]
I've also just posted #408, which is related to a previously closed issue (#286).

It does seem odd that a maintainer hasn't weighed in on this issue that's been open for over two months.

**Comment by petermikitsh** [comment]
@cwelch5 Could you chime in to the status of this project? Thanks.

**Comment by Asday** [comment]
Ayy, it looks like @tmbtech has gotten some time to work on this - his profile says he works at NFL.

A true success story.

**Comment by cwelch5** [comment]
Apologies everyone.  Been trying to find someone to help me out with this.  We appreciate the community and all the wonderful people out there supporting us.  You deserve better.

I would love to get back on this project and am trying to find time to do so.  Cleanup is first priority.  Then upgrading and API improvement.

**Comment by tmbtech** [comment]
@cwelch5 I'll DM you via slack. Let's chat about future upgrades and maybe start a wiki page. (posting here for visibility.)
