### ISSUE TITLE
Localization of tags

### ISSUE THREAD

**Issue by nomadus** [nfl/react-helmet#392]
We have a multi-language site and we would like to have tags in different languages, does react-helmet support such setup?

**Comment by Asday** [comment]
You would use the same conventions you've used elsewhere in your react app to localise strings to localise the tags.

If you were using `react-localize-redux` as follows:

```es6
<p>
  <Translate id="movie.title">Jurassic Parc</Translate>
<p>
```

Then your tags would be translated as such:

```es6
<Helmet>
  <title><Translate id="home.title">Home</Translate></title>
</Helmet>
```

And so forth.

**Comment by tmbtech** [comment]
@Asday Has the right idea.

**Comment by crisboarna** [comment]
Hi @Asday , the suggestion you provided with 
`<Helmet>
  <title><Translate id="home.title">Home</Translate></title>
</Helmet>`

does not work as it throws `Helmet expects a string as a child of <title>. Did you forget to wrap your children in braces? ( <title>{``}</title> ) Refer to our API for more information.`
Do you have any idea how to circumvent React Helmet requirement for the string int the title as it is quite troublesome to not have the head title localized?
