### ISSUE TITLE
How to avoid inline styling

### ISSUE THREAD

**Issue by vicky-blr** [nfl/react-helmet#398]
I'm using this library and using below setup and it works perfectly.
```
<Helmet>
          <style>{'body { background-color: #f2f2f2; }'}</style>
        </Helmet>
```
My question is how I can avoid this inline style here? Can we use className?? Can someone suggest alternative to above so that hardcoding can be avoided.

**Comment by AubreyHewes** [comment]
You can do this by using the body tag within Helmet:

````jsx
<Helmet>
  <body className="class" />
</Helmet>
````

**Comment by vicky-blr** [comment]
Thank you, it worked for me :)
