### ISSUE TITLE
<base /> needs to support "target" attribute

### ISSUE THREAD

**Issue by mgoulart** [nfl/react-helmet#404]
currently only `href` is supported for `<base />` tag.

**Comment by AubreyHewes** [comment]
@mgoulart The best you can do to get this change is to create a PR

https://github.com/nfl/react-helmet/blob/6e6538881cc9bbef6b72a872f997571c917b88d7/src/HelmetUtils.js#L210

https://github.com/nfl/react-helmet/blob/6e6538881cc9bbef6b72a872f997571c917b88d7/src/HelmetConstants.js#L24

**Comment by tmbtech** [comment]
@AubreyHewes @mgoulart Correct. if you want to post a PR, I can work with @cwelch5 to get it merged into master.
