### ISSUE TITLE
Explain why you deprecated having children inside your Helmet components

### ISSUE THREAD

**Issue by cesarandreu** [nfl/react-helmet#41]
Looking at the changelog, it seems it's related to #37 and doing fewer useless renders? It'd be good to have a 1 or 2 line sentence that explains the reason, instead of having to dig in.

**Comment by cwelch5** [comment]
I was trying to be brief to give a summary of the changes in the changelog.  Can you clarify - which line are you referring to in the changelog?

I think I accurately described the final behavior change in the library.  Do you feel the changes were unnecessary?  Or do you just need more of a clarification as to the problems we fixed?

**Comment by cwelch5** [comment]
Committed.  Thanks.

**Comment by cesarandreu** [comment]
Thanks for the quick update! :D
