### ISSUE TITLE
dependency of react-helmet uses legacy componentWillMount lifecycle method

### ISSUE THREAD

**Issue by jfrolich** [nfl/react-helmet#413]
The dependency react-side-effect uses componentWillMount, so react-helmet will not work in concurrentMode.

**Comment by jfrolich** [comment]
https://github.com/gaearon/react-side-effect/issues/54

**Comment by danielweck** [comment]
Looks like `react-helmet-async` is a useful alternative:
https://github.com/staylor/react-helmet-async

**Comment by goldmont** [comment]
Looks like react-side-effect [v2.0.0](https://github.com/gaearon/react-side-effect/releases/tag/v2.0.0) now uses **UNSAFE_componentWillMount**.

Thus, no more warning in the console.

**Comment by eduard-malakhov** [comment]
I confirm, after manually upgrading  react-side-effect to v2.0.0, the warning is gone.

**Comment by kevr** [comment]
> Looks like `react-helmet-async` is a useful alternative:
> https://github.com/staylor/react-helmet-async

No, it's not. Creating another package just to undeprecate something so trivial is not an alternative, it's a fallback.

**Comment by samuraime** [comment]
before `react-helmet` update its dependency, a temporary workaround in package.json
```
  "resolutions": {
    "react-side-effect": "^2.1.0"
  }
```

**Comment by cwelch5** [comment]
Thanks for everyone's patience. We are actively working on 6.0.0 release. 6.0.0-beta.2 is available and will work with the latest React version.

**Comment by dantman** [comment]
> so react-helmet will not work in concurrentMode

It doesn't sound like the issue as originally opened was actually fixed. The only difference is a switch from `componentWillMount` (which emits a depreciation notice and won't work in concurrent mode)  was replaced with <code>**UNSAFE**_componentWillMount</code> (that doesn't emit a deprecation notice; but still does not work in concurrent mode).

**Comment by miquelvir** [comment]
Why is this closed? Seems that still not working properly (https://github.com/bbc/simorgh/issues/3893#issuecomment-730702092) since we are getting the warning with ^6.1.0.

**Comment by adamnorbacker** [comment]
@cwelch5 its still the same issue.
