### ISSUE TITLE
React Helmet does not work inside error boundary correctly

### ISSUE THREAD

**Issue by reduxdj** [nfl/react-helmet#422]
Our DefaultHelmet is never replaced by any content after first render for SSR apps.

```
    <ErrorBoundary>
    <DefaultHelmet />
    <Main />
 </ErrorBoundary>
```

**Comment by tmbtech** [comment]
Hi @reduxdj - 

Can you post a snippet of what is in side of <DefaultHelmet /> ? 
Do you have another Helment tag inside of <Main />?

I don't really have enough context to see if there is a problem with helmet or the SSR implementation.

**Comment by reduxdj** [comment]
Sorry, this isn't related to the react-helmet component but a problem with the ErrorBoundary preventing child components from rendering.

See https://github.com/apollographql/apollo-client/issues/4639
