### ISSUE TITLE
Publish for Maximum call stack #373

### ISSUE THREAD

**Issue by giannif** [nfl/react-helmet#431]
Not to nag, but been waiting for this to get published: https://github.com/nfl/react-helmet/issues/373 

According to the last comment, it should have been released two weeks ago. [npm](https://www.npmjs.com/package/react-helmet/v/5.2.0) says the last publish was about then, but there is no change in version. If there's no pending patch, I can switch libraries. Looking for clarity here so I can fix a critical bug we've had while away on holiday.

**Comment by tmbtech** [comment]
Hi, we published a beta build. Try running that? 
https://www.npmjs.com/package/react-helmet

`npm install react-helmet@6.0.0-beta` should do it.

**Comment by giannif** [comment]
Okay, had a feeling the beta was the way to go, but was unsure about its stability. Thanks @tmbtech

**Comment by tmbtech** [comment]
Check the comments in https://github.com/nfl/react-helmet/pull/421 on the breaking change

**Comment by tmbtech** [comment]
Sorry for the lack of communication, it's playoff season and we are swamped. Looking forward to your feedback on the beta, it should be pretty stable.
