### ISSUE TITLE
How to overwrite a tags 

### ISSUE THREAD

**Issue by pkumar01** [nfl/react-helmet#435]
I am using react-helmet for my project and needed help on SEO changes for my website, i want to add a link when data gets served from api and that link should also update on pagination i can see that happening on browser elements tab but when i do page source it shows the old content only. 

when i tried "onChangeClientState" it shows me that data has been updated but again on view source it is not reflecting

**Comment by digizimm** [comment]
How does it relate with react helmet?

**Comment by pkumar01** [comment]
Because updating meta tags in head is done via react-helmet, closing this ticket i am assuming there is no positive response to my query.
