### ISSUE TITLE
Unclear purpose of helmet

### ISSUE THREAD

**Issue by stefanoborini** [nfl/react-helmet#449]
Sorry to everybody and please forgive me for the question but I am not particularly versed in web development.

I don't get the purpose of this package. What problem is it trying to solve?

**Comment by Nattfarinn** [comment]
As far as I can tell, it is syntax sugar that replaces manual manipulation of outside DOM (in this case: `<head>`) from within of React component. Helmet still does it but at least you don't have to, so you keep your own components unpolluted.

**Comment by tmbtech** [comment]
@stefanoborini check out this article. https://open.nytimes.com/the-future-of-meta-tag-management-for-modern-react-development-ec26a7dc9183?gi=176d3fe608fa
