### ISSUE TITLE
add script property to helmet?

### ISSUE THREAD

**Issue by nikhedonia** [nfl/react-helmet#45]
I started to play around with helmet in my isomorphic app and realized how much it simplifies meta-data-related stuff.
I now believe it would be very useful to collect scripts through helmet to increase modularity of SPAs even more. It also would make it easier to manage multiple SPA.

Let me elaborate on this idea:

If you have a eg. Blog-app, it concerns me to bundle everything up and send it to the client.
I consider it good practice to make multiple bundles for eg. the user-view and the admin-view for mainly 2 reasons:
- minimize size of bundle
- increase security by not exposing admin-script-logic to the client

With webpack or browserify you can explicitly define what and how to bundle together.
Still you need to rely to some logic (plugins) to figure out which pages need which bundles and embed this bundles to your server-rendered html. I think Helmet provides a good opportunity to automate this task and remove the need for certain plugins.

Once you have Helmet figured out which Scripts are required by which Page, you could even dynamically bundle the scripts with webpack if not found/up-to-date. 

Example(sketch):
```js
//blog.js

import {stores,actions,controller} from "blogController"

export const Blog = ({title,meta,children})=>(
 <div>
  <Helmet meta={meta} title={title}  script={[{src:__filename}]} />
  <Link to="allPosts/" />
  {children}
  </div>
)

export const routes = (
  <Route component={Blog} >
    // <Route /> some more routes
  </Route> )
```
```js
//admin.js
import {blog,routes:blogRoutes} from "./blog"
// controller, components, routes...
```
```js
//server.js

/*do the routing */
const body = renderToString(myComponent);
const {meta,link,title,scripts} = Helmet.rewind();
const html = `
<html>
<head>
${title}
$(meta} 
${link}
</head>
<body>
${body}
${scripts} 
</body>
</html>

//check if scripts exists and are up-to-date otherwise compile...
res.send(html)
```

Once a script param is introduced into helmet, there are two question left:
- how should it behave on the client?
    I suggest implementing the script-param as an array of object with following properties:
    - type : string => the type of the script eg. "text/coffescript"
    - load : boolean  =>   should helmet inject a script tag on the client (on first occurrence)
- should multiple occurences of Helmet scripts params on different places override each other or compose?  
    I would suggest the latter one...

What do you think?

**Comment by cwelch5** [comment]
This is a very interesting idea that is well thought out.  I'm not too familiar with the plugins you are discussing for determining which bundles to pair with pages.  Could you provide some examples?  I'm wondering if adding this to Helmet would be any better than the existing libraries out there.

My initial thought is the original goal of Helmet was to manage content that is exclusive to the document head.  And while this is a great idea, I'm not sure at this point if it fits here, or in another library based off react-side-effect, or if this need is better served by the other solutions out there.

**Comment by cwelch5** [comment]
We have basic support for `script` tag in Helmet 2.1.0.  We'll look into adding more advanced support in the future.  Thank you for your inquiry.
