### ISSUE TITLE
Consider deprecating this REPO and removing off NPM

### ISSUE THREAD

**Issue by reduxdj** [nfl/react-helmet#451]
If i had a dollar every time my boss came into tell me there's a problem with the metadata, I'd be a really rich person.

This component has serious problems with thread leaks and showing wrong metadata, and other solutions are problematic too....

The renderStatic method of this app is very scary (side-effects and all), and although we are trying to render our app as a string this module leaks metadata to the wrong request.

**Comment by brettimus** [comment]
Could you elaborate? Provide links to existing issues or perhaps steps to reproduce memory leaks, incorrect metadata, etc?

If not, could you change the title of this issue?

I'm trying to put myself in the shoes of the maintainers here, and suggesting the removal of their repo from NPM seems extreme, unless you provide well-warranted and well-documented reasons to do so.

**Comment by omaksi** [comment]
I suggest at least putting a not-maintained or deprecated notice on top of the README. Maybe also a suggestion of a maintained alternative like react-helmet-async, or similar.

**Comment by reduxdj** [comment]
For example, here's somebody who's solved this renderStatic fiasco and made a PR months ago, and the maintainers of this repo have ignored the pull requests, for 6 months now: 
(see https://github.com/openameba/react-safety-helmet)

**Comment by reduxdj** [comment]
@omaksi I agree with your sentiment. It's difficult to understand when something is branded by one of the bigger sports organizations in the world, and the project's maintainers just bail on it all together.

**Comment by CanRau** [comment]
Anyone experience with [react-head](https://github.com/tizmagik/react-head)?

**Comment by IanVS** [comment]
I'd like to give a shoutout to @tmbtech for stepping up and merging some PRs.  👏
