### ISSUE TITLE
meta title tag not being updated

### ISSUE THREAD

**Issue by LinusGeffarth** [nfl/react-helmet#457]
I've been setting my react.js SPA's page titles by doing:

    document.title = {some title}

...so far and it worked fine. Now, I also wanted to update the `meta` `title` tag and so I decided to install react-helmet.  
In my component, I've imported `Helmet` and did:

    render() {
      {/* ... */}
      return (
        <div>
          <Helmet>
            <title>{docTitle}</title>
            <meta name="title" content={docTitle} />
          </Helmet>
          {/* ... */}
        </div>
      )
    }

When opening the page, I saw that the document title is properly updated, but when inspecting the elements in the browser, I noticed that `<meta name="title"` is not being updated, while a few lines down, `<title>` *is* updated.

What am I doing wrong here?

**Comment by LinusGeffarth** [comment]
In my `<head>` code, I added the following tag in the `index.html` file:

    <meta name="title" content="Default Title">

When updating that meta tag using react-helmet, I still saw that tag un-updated in the index.html file when inspecting the elements in my browser.  
However, what I did not notice, is that at the very bottom of the `<head>`, Helmet apparently added this tag instead:

    <meta name="title" content="Default Title" data-react-helmet="true">

I'm guessing (and hoping) that this will be crawled by search engine bots.

**Comment by petervavro** [comment]
How did you solve this, please?
