### ISSUE TITLE
Include minified script

### ISSUE THREAD

**Issue by bkniffler** [nfl/react-helmet#46]
Hi, 
It would be great if you provided a minified version of react-helmet within the package, like `react-helmet/dist/react-helmet.min.js`. That would for example help optimizing for webpack:
https://christianalfoni.github.io/react-webpack-cookbook/Optimizing-rebundling.html

**Comment by cesarandreu** [comment]
I think the reason that's suggested for React is because it's a reasonably large library, but react-helmet is pretty tiny in comparison, so I would conjecture that there wouldn't be huge gains.

**Comment by cwelch5** [comment]
Very interesting article @bkniffler.  Thanks.  But I agree with @cesarandreu, minifying Helmet won't significantly decrease webpack bundling in a local development environment.
