### ISSUE TITLE
Throws warnings in React 16.9 and will not work with React 17

### ISSUE THREAD

**Issue by mikecousins** [nfl/react-helmet#465]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Throws warnings with React 16.9+ and will not work with React 17.

**If the current behavior is a bug, 
please provide the steps to reproduce and if 
possible a minimal demo of the problem. 
Your bug will get fixed much faster if we can run your 
code and it doesn't have dependencies other than React and react-helmet. 
Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or 
CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
No warnings and should work.

**Which versions of React and react-helmet, and which browser / OS are affected by this issue? 
Did this work in previous versions of React and/or react-helmet?**
React 16.9+, any version of react-helmet, any browser/os.

Here is the warning thrown now:

Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: SideEffect(DocumentTitle)

**Comment by mikecousins** [comment]
Whoops, this is react-document-title, not react-helmet.

**Comment by mikecousins** [comment]
Still valid actually, react-helmet also depends on react-side-effect. Looks like we need to wait for them to update.

**Comment by AlmeroSteyn** [comment]
Ran into the same this morning with the package. 

FYI this comment on the issue logged on react-side-effect: https://github.com/gaearon/react-side-effect/issues/54#issuecomment-520056590

Suggestion there is to migrate away from that package.

**Comment by danielweck** [comment]
Duplicate: https://github.com/nfl/react-helmet/issues/413

**Comment by bitttttten** [comment]
so TL;DR migrate to react-helmet-async?

**Comment by MarioRicalde** [comment]
Today I spent some time migrating some of my components that were depending on `componentWillMount` - turns out that my SEO component had a dependency on it without noticing.

**Comment by hiyangguo** [comment]
I force installed `react-side-effect@2.1.0` in my package with
```
npm i  react-side-effect@2.1.0
``` 
It work fine.
And when time will fix it?

**Comment by AlmeroSteyn** [comment]
From what I can see, the change in `react-side-effect` only silences the warning. It will still break in React 17.

**Comment by cdeutsch** [comment]
> From what I can see, the change in react-side-effect only silences the warning. It will still break in React 17.

It looks like they renamed to the `UNSAFE_` versions, which WILL continue to work in React 17

**Comment by sudomaxime** [comment]
> I am getting this error as well using react 16.9.0

I ended-up using react-helmet-async instead, mainly for server side rendering purposes.

**Comment by eriklharper** [comment]
What's going on with this ticket?  Do you plan on upgrading `react-side-effect` to 2.0, which addresses this issue?  If you do that it will require you to upgrade to React 16, which you're going to want to do eventually anyway right?

Or, following Dan's advice to move away from using this might also be wise: https://github.com/gaearon/react-side-effect/issues/54#issuecomment-520056590

**Comment by AlmeroSteyn** [comment]
> It looks like they renamed to the UNSAFE_ versions, which WILL continue to work in React 17

Yeah you are right, they are only removing the actual lifecycle hooks. However these lifecycle hooks have been deprecated due to possible problems with the upcoming concurrent mode, so this is not something one ideally wants to have "hidden" in applications that use this package. 

Dan's advice in the linked comment would probably be the best way. Although it is a much costlier fix.

**Comment by asotog** [comment]
Installed today and getting same warning

**Comment by jonnypage-d3** [comment]
I also installed today and am getting the same warning

**Comment by ahmed-rezk-dev** [comment]
Me also!!!

**Comment by suhanw** [comment]
Me too

**Comment by cwelch5** [comment]
Thanks for everyone's patience.  We are actively working on 6.0.0 release.  6.0.0-beta.2 is available and will work with the latest React version.  We'll also be looking to see how this library can work with React 17.

**Comment by koalex** [comment]
Still same problem on React 17...

**Comment by matewka** [comment]
The problem is still present in react-helmet@6.1.0.

**Comment by garethtalty** [comment]
February 2022 and this is still an issue in react-helmet@6.1.0.

Both this and https://github.com/nfl/react-helmet/issues/413 have been closed while this issue still exists.

**Comment by cdeutsch** [comment]
@garethtalty I ended up switching to [react-helmet-async](https://www.npmjs.com/package/react-helmet-async)

**Comment by garethtalty** [comment]
> @garethtalty I ended up switching to [react-helmet-async](https://www.npmjs.com/package/react-helmet-async)

Thanks @cdeutsch, hoping the upgrade path is minimal?

**Comment by cdeutsch** [comment]
> hoping the upgrade path is minimal?

It's been 2+ years so I don't remember, but hopefully not remembering is a good sign. lol

**Comment by Robin-Hoodie** [comment]
2024 checking in here - seems to still be an issue in `6.1.0`
