### ISSUE TITLE
Upgrade `react-side-effect`

### ISSUE THREAD

**Issue by voodoocreation** [nfl/react-helmet#495]
**Do you want to request a *feature* or report a *bug*?**
Bug: currently the version of `react-side-effect` that's currently used is causing deprecated warnings to be thrown in `react@16` due to its usage of `componentWillMount`.

**What is the current behavior?**
When mounting components in a `react@16` or above environment, deprecated warnings are thrown.

**If the current behavior is a bug, 
please provide the steps to reproduce and if 
possible a minimal demo of the problem. 
Your bug will get fixed much faster if we can run your 
code and it doesn't have dependencies other than React and react-helmet. 
Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or 
CodeSandbox (https://codesandbox.io/s/new) example below:**
Use `Helmet` in a `react@16` environment or above.

**What is the expected behavior?**
Warnings are not thrown.

**Which versions of React and react-helmet, and which browser / OS are affected by this issue? 
Did this work in previous versions of React and/or react-helmet?**
React@16+

**Comment by Askadias** [comment]
+1

**Comment by jonsadka** [comment]
+1

**Comment by sms1989** [comment]
+1

**Comment by himynameisdave** [comment]
+1

**Comment by cwelch5** [comment]
Thanks for everyone's patience. We are actively working on 6.0.0 release. 6.0.0-beta.2 is available and will work with the latest React version.
