### ISSUE TITLE
Bug: After updating to 6.0.0-beta, importing Helmet doesn't work with Enzyme

### ISSUE THREAD

**Issue by teslerbar** [nfl/react-helmet#504]
[Bug]

**If the current behavior is a bug, 

After upgrading to version 6.0.0-beta, and change to named import, instead of default import - import { Helmet } from 'react-helmet'

Enzyme is throwing the following error: 
"TypeError: Enzyme::Selector expects a string, object, or Component Constructor".

It seems that the named import doesn't return a valid element that can be rendered by React.

please provide the steps to reproduce and if 
possible a minimal demo of the problem. 
Your bug will get fixed much faster if we can run your 
code and it doesn't have dependencies other than React and react-helmet. 
Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or 
CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of React and react-helmet, and which browser / OS are affected by this issue? 
Browser: Chrome - Version 79.0.3945.130 

"react-helmet": "6.0.0-beta",
"react": "16.12.0",
"enzyme": "3.8.0",
"enzyme-adapter-react-16": "1.15.2",
"jest": "20.0.4",
"babel-jest": "20.0.3"

Did this work in previous versions of React and/or react-helmet?**
Yes. It was working, with default imports, up until updating to version 6.0.0-beta

**Comment by cwelch5** [comment]
@teslerbar 6.0.0-beta didn't support react@16.12.0, but 6.0.0-beta.2 should support that version now.  Please try that with Enzyme and the named import.  Thanks.
