### ISSUE TITLE
Please update docs: do overrides override everything?

### ISSUE THREAD

**Issue by Faithfinder** [nfl/react-helmet#556]
It's unclear from the docs, and I'm too lazy to check myself.
In this example:
```javascript
<Parent>
    <Helmet>
        <title>My Title</title>
        <meta name="description" content="Helmet application" />
    </Helmet>

    <Child>
        <Helmet>
            <title>Nested Title</title>
        </Helmet>
    </Child>
</Parent>
```
Does my page still have a meta description, or did it get deleted? i.e, is the output
```html
<head>
    <title>Nested Title</title>
    <meta name="description" content="Helmet application">
</head>
```
or
```html
<head>
    <title>Nested Title</title>    
</head>
```

**Comment by cwelch5** [comment]
Your first assessment is correct 🎉

**Comment by Faithfinder** [comment]
I mean, thank you, I'm happy to know, but shouldn't the docs actually be updated? I can't imagine I'm the only one who found that confusing

**Comment by cwelch5** [comment]
@Faithfinder I would like to make it clearer if possible, but I dont understand how. Perhaps you have some suggestions?

**Comment by Faithfinder** [comment]
Changing the examples like in my question should illustrate the concept. (there's what, 1 line difference?).
Also a phrase along the lines of "Helmet leaves the tags not specified in it alone: if you use it to set a "meta-description" down the component tree it will leave the title intact".

Though it does leave me with the question "What if I want to delete a tag?". Don't have a usecase, just thinking about the options.
