### ISSUE TITLE
Page title not updating immediately after render on Chrome Desktop

### ISSUE THREAD

**Issue by cbdeveloper** [nfl/react-helmet#560]
**Do you want to request a *feature* or report a *bug*?**

(POSSIBLE) BUG / WEIRD BEHAVIOR

**What is the current behavior?**

I'm rendering the following structure:

- The `App` component renders a `<Helmet/>` with a default `<title/>`
- It calls some API and when the data arrives. It renders a `<Component/>`
- The component renders its own `<Helmet/>` with its own `<title/>` changing the page title.

```
<App>

  <Helmet>
    <title>DEFAULT TITLE</title>
  </Helmet>

  // APP MAKES SOME API CALLS AND ONLY RENDERS <Component>
  // WHEN DATA ARRIVES

  {  dataFromAPI &&
    <Component>
        // THE <Helmet/> IS REPRESENTED HERE, BUT IT IS RENDERED BY <Component/>
        <Helmet>
          <title>COMPONENT TITLE</title>
        </Helmet>  
    </Component>
  }

</App>
```

The fact is that from `Component`, on Chrome Desktop, we get this:

```
  function Component() {

    useEffect(()=>{
      console.log(document.title);                          // Logs  "DEFAULT TITLE"
      setTimeout(()=>console.log(document.title),0);        // Logs  "COMPONENT TITLE"
    },[]);

    return(
       <React.Fragment>
          <Helmet>
             <title>COMPONENT TITLE</title>
          </Helmet>
           // SOME OTHER STUFF
       </React.Fragment>
    );
  }
```

**WEIRD BEHAVIOR ON DESKTOP CHROME**

This weird behavior is happening on `Chrome Version 81.0.4044.129 (Official Build) (64-bit)`
And `Firefox 75.0 (64-bit)` is working fine. This is all I have tested so far.

How is it possible that from a `useEffect` from a `<Component/>` that just rendered a `<Helmet/>` changing the page title, I'm logging the `DEFAULT TITLE` which was rendered by a parent?

When I log it inside a `0ms setTimeout()`, it logs the proper `COMPONENT TITLE`

**What is the expected behavior?**

I would be able to log the updated title from the `useEffect` immediately, without using a `setTimeout`.

**Which versions of React and react-helmet, and which browser / OS are affected by this issue? 
Did this work in previous versions of React and/or react-helmet?**

**REPRODUCIBLE EXAMPLE**

I tried my best to create a CodeSandbox with this issue, but I wasn't able to reproduce it. Anyway, I'm getting this behavior on my local environment. `Chrome Desktop` does not work properly. `Firefox` works fine.

CHROME:

![image](https://user-images.githubusercontent.com/43407798/81717679-be69aa80-9472-11ea-9d71-3dcba852fa09.png)

FIREFOX:

![image](https://user-images.githubusercontent.com/43407798/81717724-d0e3e400-9472-11ea-90ee-9cdc8c2089af.png)

**QUESTION**

Is this a known issue? Is there a way to "fix" it for the `Chrome Desktop` browser?

**MY USE CASE**

I need to access the updated title inside the `useEffect` in order to send an Analytics Page View hit from my web app, which is an SPA. So I need to use the current title to send it over the analytics `gtag` call.

```
"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-helmet": "^6.0.0",
```

**Comment by ifedyukin** [comment]
@cbdeveloper you can pass `defer={false}` to Helmet component. It solved the same problem for me.

**Comment by DuudeXX8** [comment]
Same issue.Do you have any solution about this bug?

**Comment by cbdeveloper** [comment]
I don't have a definitive solution to this yet. This bug was a problem to me because I send **analytics** events from those `useEffect` and I was getting lots of `page_title: not set` in my reports. I feel that the `setTimeout(() => ... , 0)` definitely helps, but sometimes I'm still getting `page_title: not set`, which means the code wasn't able to read the `document.tile`. I'm even thinking about trying with `100 or 200ms` timeout to see if it improves. Anyway, that is how I'm dealing with this so far.

**Comment by meness** [comment]
I didn't test this yet. A workaround is you put analytics scripts at the bottom of the `index.html` exactly before `</body>`.

**Comment by AubreyHewes** [comment]
The most prominent idea here is that the problem is due to react-helmet. 

It is for the topic; due to the react render process and how to understand it (feel that the setTimeout(() => ... , 0) definitely helps). For other comments the usage/when and how of applying tracking api.

 * React useEffect is not a one time render; it will console log once and after the timeout again (next tick; is most probably after the render of helmet; maybe)
 * Why are you relying on `document.title` for page view?
 * Why are you doing page view analytics yourself, instead of relying on a proven library?
 * Generally you do not send the title to the tracking api just the page view, i.e. the route.  Though for a SPA you may need to send more details (as it is a SPA).
 * The page view should be sent on route change; i.e. utilize routing. (in a SPA on route load if the route has the data then send the page view; not before)

SPA blueprints with page analytics logging:

1. on route do a pageView (url only)
1. on route wait for data and do a pageView (url and possible other data; i.e. title from the data; not the document.title)

There is a react component to solve a lot of the issues.

Let me know if I missed something! :sheep:

**Comment by cbdeveloper** [comment]
@AubreyHewes thanks for the ideas.

Since my app is an SPA, `gtag` won't fire `pageViews` on client route changes. That's why my code needs to implement this behavior. For a multiple page APP rendered on the server, it would be possible to rely solely on the `gtag` default `<script/>` from Google Analytics. That would fire every time a page was rendered.

Everything is working fine. But I'll definitely use the `title` that comes on my `data` rather than relying on the `document.title` to update (which is working fine, but not in the order/sync I was expecting it to).

Thanks again.

**Comment by AubreyHewes** [comment]
@cbdeveloper I fully understood that your app was a SPA and `gtag` wont fire changes. With `pageView` and `page view` I was trying to be agnostic. i.e. when you want to register a page view you use the api for it. So on route change use your analytics api to register a page view.
There are libraries for this.. like react-ga and such. Though you still need to feed them "extra" data if required. In your case the title.

As stated the `document.title` is updated by react-helmet but on only on the next render... so your expectation of it being correct on the first render is unfortunately the reason. This is a common misconception of react-helmet.

Is your issue resolved? If so can you then resolve the issue?

**Comment by cbdeveloper** [comment]
Did not know about the `react-ga` package. Will give that a try. What I can take from this issue is that I can't rely on the assumption that the browser will update the `document` properties synchronously, so I have to work around that. I'll close this issue. Thank you for your help.

My conclusion is:

- `<Component/>` rendered a new Page `<Helmet/>`
- `useEffect` from `<Component/>` must be aware that `document` properties may not have been update at this point.

**Comment by AubreyHewes** [comment]
> What I can take from this issue is that I can't rely on the assumption that the browser will update the document properties synchronously

Remember your React lessons.. how does React work?.. assumptions are not part of the process.

**Comment by Bhushan-WhiteBoxData** [comment]
@cbdeveloper Did you figure out a work around for this? It is causing a ton of SEO issues for us since bots are going with the default title as that gets caught before the actual value gets passed.
