### ISSUE TITLE
update @types/react-helmet to 6.1.0

### ISSUE THREAD

**Issue by artygrand** [nfl/react-helmet#595]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
update @types/react-helmet to 6.1.0 please

**Comment by AubreyHewes** [comment]
The types are not (yet) maintained by this project.

See https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-helmet/

Feel free to PR the types to this lib and remove them from DefinitelyTyped

**Comment by josejulio** [comment]
There is already [v6.1.0](https://www.npmjs.com/package/@types/react-helmet/v/6.1.0) for `@types/react-helmet `
