### ISSUE TITLE
no docs on how client needs to use peek() instead of rewind()

### ISSUE THREAD

**Issue by bdefore** [nfl/react-helmet#61]
at least you get an error though: `Uncaught Error: You may ony call rewind() on the server. Call peek() to read the current state.` but then when you do the following:

```
import helmet from 'react-helmet';

export default class Header extends Component {
  componentWillMount() {
    console.log('peek', helmet.peek());
  }
}
```

you get `undefined` ... can you elaborate client side use for reading meta tags?

**Comment by cwelch5** [comment]
In your example you need to use Helmet as a component in your render function, and you need to pass a property that you would like to be used.  For meta tags, it would be something like this:

```
import React from "react";
import Helmet from "react-helmet";

export default class Application extends React.Component {
    render() {
        return (
            <div className="application">
                <Helmet
                    meta={[
                        {"name": "description", "content": "Helmet application"},
                        {"property": "og:type", "content": "article"}
                    ]}
                />
                ...
            </div>
        );
    }
};
```

Helmet.rewind() is used on the server.  Helmet.peek() can be used at any time, but will only provide defined properties if you call this after the Helmet receives the props.

**Comment by cwelch5** [comment]
Also, `peek()` comes from `react-side-effect`, you can refer to the README there - https://github.com/gaearon/react-side-effect

Hope that helps.
