### ISSUE TITLE
a community thing; issue/PR maintenance

### ISSUE THREAD

**Issue by AubreyHewes** [nfl/react-helmet#621]
**Do you want to request a *feature* or report a *bug*?**

No and yes, more a community thing.

**What is the current behavior?**

Issues are unmaintained or never closed, a forest.

**What is the expected behavior?**

Issues are maintained/tagged/assigned/closed

**How would you solve this**

I do not mind being giving the rights / collaborating for tagging issues as "information need", closing unusable issues, closing and linking already resolved issues. etc.

**Why would you do this**

@cwelch5 It is a pet peeve, everytime I look the issues are boundless and PRs are ignored. It is uncertain which issues/PR are actually valid for the current codebase

**Comment by AubreyHewes** [comment]
omg just browsing but...
ie.
https://github.com/nfl/react-helmet/issues/522 is solved?... but still open?

**Comment by jens-duttke** [comment]
Seems like this project is dead. But what are the alternatives?

**Comment by cwelch5** [comment]
Thank you @AubreyHewes , I wish there was enough folks over here and enough time to get this library back to where it was.  In the meantime, there is a very solid fork that is more up to date that I would recommend: https://github.com/staylor/react-helmet-async

**Comment by AubreyHewes** [comment]
@cwelch5 That is all good and nice.. but in the meantime.. issues/prs. Change the readme to say it is a dead project. Else archive the project (killing issues and changes)?

Change the readme to point developers to the promoted https://github.com/staylor/react-helmet-async solution

You shut down the only issue that was discussing this point. In the meantime.. unanswered PRs and issues
