### ISSUE TITLE
Link previews not working correctly

### ISSUE THREAD

**Issue by Puyodead1** [nfl/react-helmet#624]
I have a website that uses React-Router for multiple pages and I am trying to have different meta tags for each page, but all the meta testers ive tried failed to detect any of the meta tags including https://developers.facebook.com/tools/debug.

My index.html:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <meta property="og:type" content="website" />
    <meta name="theme-color" content="#9b59b6" />
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root" class="d-flex flex-column min-vh-100"></div
  </body>
</html>
```

My Home.js:
```jsx
import React from "react";
import { Helmet } from "react-helmet";
import { Toast } from "primereact/toast";

export default class Home extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <div className="app">
        <Helmet>
          <title>Home</title>
          <meta name="title" content="Home" />
          <meta
            name="description"
            content="Page description"
          />

          <meta property="og:type" content="website" />
          <meta property="og:url" content="https://website.com/" />
          <meta property="og:title" content="Home" />
          <meta
            property="og:description"
            content="Page description"
          />
          <meta property="og:image" content="/Profile_Picture.png" />

          <meta property="twitter:card" content="summary_large_image" />
          <meta property="twitter:url" content="https://website.com/" />
          <meta property="twitter:title" content="Home" />
          <meta
            property="twitter:description"
            content="Welcome to moguldevs.xyz, the website for all of Ittim's projects like TycoonMogul, and his digitalized list of educations, awards, & certifications!"
          />
          <meta property="twitter:image" content="/Profile_Picture.png" />
        </Helmet>

        <div className="container text-center">
          ... page content
        </div>
      </div>
    );
  }
}
```

App.js:
```jsx
import {
  BrowserRouter as Router,
  Switch,
  Route,
  NavLink,
  Redirect,
} from "react-router-dom";
import Home from "./Home";
import "./Styles.css";

const App = () => {
  return (
    <Router>
      <NavLink to="/" className="nav-link" activeClassName="active" exact>Home</NavLink>
      <Switch>
        <Route path="/" exact>
          <Home />
        </Route>
      </Switch>
    </Router>
  );
};

export default App;
```

**Comment by AubreyHewes** [comment]
@Puyodead1 If the site is not static then you may expect this. As you are using client side routing (SPA) those kind of microdata tests require a proper server response... your server is probably responding as a 404 for the path in question.

To help finding the issue add a usable/reproducible code example on https://codesandbox.io/ and link it here.

Without the usable/reproducible code example there is not that much chance that anyone will know why you have a problem. It works on my machine.

Any issues that may be bugs will probably never be helped:

> I wish there was enough folks over here and enough time to get this library back to where it was. In the meantime, there is a very solid fork that is more up to date that I would recommend: https://github.com/staylor/react-helmet-async

**Comment by ursnj** [comment]
Im trying to populate <Helmet/> with dynamic data, ( from API ) but its not working when i share page in social networks like Facebook and Twitter, i think the purpose of Metatags are not full filling with this.

If some one has any solution please put it here.

you can find the issue here in my Website : https://www.watchpartys.com/watchpartys/watch/93038ad4-dbb5-462f-aeed-efbd91b0ff45

**Comment by Puyodead1** [comment]
I'm going to close this issue since I'm not working on the project where I had this issue anymore.

**Comment by haresh6x** [comment]
> Im trying to populate with dynamic data, ( from API ) but its not working when i share page in social networks like Facebook and Twitter, i think the purpose of Metatags are not full filling with this.
> 
> If some one has any solution please put it here.
> 
> you can find the issue here in my Website : https://www.watchpartys.com/watchpartys/watch/93038ad4-dbb5-462f-aeed-efbd91b0ff45

Hi

Did you ever find a solution? My project is made using CRA and I am having the same problem.

**Comment by alpesh-yorkie** [comment]
Having the same issue, has anyone found any solution?

**Comment by AlpeshB08** [comment]
Having the same issue, has anyone found any solution?

**Comment by Real-Music** [comment]
I'm having the same issue...
