### ISSUE TITLE
Twitter image never show

### ISSUE THREAD

**Issue by ghost** [nfl/react-helmet#630]
**Do you want to request a *feature* or report a *bug*?**
a bug
**What is the current behavior?**
Other share platforms image works, for example, Facebook but Twitter doesnt
**If the current behavior is a bug, 
please provide the steps to reproduce and if 
possible a minimal demo of the problem. 
Your bug will get fixed much faster if we can run your 
code and it doesn't have dependencies other than React and react-helmet. 
Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or 
CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**
I dont know for sure if it is bug but i have tried multiple times.
Expected behavior image card should display 
Meta tags 
```
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:title" content="Parade of Fans for Houston’s Funeral"/>
<meta name="twitter:description" content="NEWARK - The guest list and parade of limousines with celebrities emerging from them seemed more suited to a red carpet event in Hollywood or New York than than a gritty stretch of Sussex Avenue near the former site of the James M. Baxter Terrace public housing project here."/>
<meta name="twitter:image" content={ShareItem.image} />
<meta name="twitter:image:alt" content="twitter image"/> 
```
**Which versions of React and react-helmet, and which browser / OS are affected by this issue? 
I am using Razzle 4.0.0 react-helmet 6.1.0
Did this work in previous versions of React and/or react-helmet?**
No didnt use it on previous versions

**Comment by AubreyHewes** [comment]
@Ghaleb-alnakhlani 

You have to give some more information. What you want works for most developers.

To help finding the issue add a usable/reproducible code example on https://codesandbox.io/ and link it here.

Without the usable/reproducible code example there is not that much chance that anyone will know why you have a problem. It works on my machine.

Any issues that may be bugs will probably never be helped:

> I wish there was enough folks over here and enough time to get this library back to where it was. In the meantime, there is a very solid fork that is more up to date that I would recommend: https://github.com/staylor/react-helmet-async

**Comment by RodrigoPrior** [comment]
Hi, 

If I understood, this is a thread similar to this fully detailed issue: https://github.com/gatsbyjs/gatsby/issues/22206

It seems that social platforms (Fb, Tw, Whatsapp etc) limits the bytes download in page html/head, so if helmet render tags to late (in the end of head), social buttons are not rendered correctly, as described here: https://developers.facebook.com/docs/sharing/webmasters/crawler/

```
Any Open Graph properties need to be listed before the first 1 MB of your website or app, or it will be cutoff.
```

A 1Mb download its a lot but its not clear if it includes css, js etc...if yes, and helmet render tags after that (eg: @emotion/css), it will certainly hit this limit.

I have found similar (or almost similar, please review) issues:

* https://github.com/nfl/react-helmet/issues/624
* https://github.com/nfl/react-helmet/issues/514
* https://github.com/nfl/react-helmet/issues/489
* https://github.com/nfl/react-helmet/issues/442
* https://github.com/nfl/react-helmet/issues/353
* https://github.com/nfl/react-helmet/issues/98


![screenshot](https://user-images.githubusercontent.com/547987/107897207-566f5580-6f17-11eb-8825-53426245fa3b.png)

**Comment by ghost** [comment]
For anyone facing the problem in the future, this is how I solved it
set the meta data width and height exactly like below 
```
 <meta property="og:image:width" content="600" />
 <meta property="og:image:height" content="314" />
<meta property="og:image" content={image}/>
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:title" content={title}/>
<meta name="twitter:description" content={description}/>
```
so after setting the width to 600 and height to 314 it worked
also check @RodrigoPrior solution

**Comment by Sitaras** [comment]
So with react-helmet can't update the og:image, right ?
