### ISSUE TITLE
NOTICE: This project is dead and no longer maintained

### ISSUE THREAD

**Issue by AubreyHewes** [nfl/react-helmet#631]
Alternative (proposed) is https://github.com/staylor/react-helmet-async

See for more information the discussion @ https://github.com/nfl/react-helmet/issues/621#issuecomment-747575722

Unfortunately, it seems, there is no one that cares (who can/will close/archive the project) to stop issues/PRs on this project.

Myself I use nextjs for most solutions these days. My interest in this project waned when react-static became obsolete (few years ago).

**Comment by cwelch5** [comment]
I'll add that repo to the README, that's a great idea.  We are not ready to archive as there is a promising v7 thread that we are working on.

**Comment by AubreyHewes** [comment]
@cwelch5 ah cool, I was wondering about something like that

I apologize if the issue was overbearing and irritating... just the state of the project/issues... well you know.

Have always loved this project, and will always appreciate the work put in to it by everyone!
