### ISSUE TITLE
As high-order component

### ISSUE THREAD

**Issue by srph** [nfl/react-helmet#67]
Hey there, this project is awesome.

Anyway, I think it would be nice to have / use `react-helmet` as HOC.

``` es6
@helmet(props => ({ title: `${props.user.name}'s profile` }))
class HomeView extends Component {
```

**Why?**
I don't really want to pollute my render, and I think it would be easier where the page title lies.

**Comment by cwelch5** [comment]
As a decorator, yes, that's an interesting idea.  PRs are welcome!

**Comment by srph** [comment]
Not necessarily a decorator. No problem, but can we keep this issue open til the PR is merged (so I don't forget; or if anybody else wants to take on the issue)?

**Comment by potench** [comment]
Yes, I will mark this as a feature request and leave it open.

**Comment by artfuldev** [comment]
@srph Do you need only document title? Have you taken a look at https://github.com/gaearon/react-document-title?

I'm interested to work on this.

**Comment by damianobarbati** [comment]
Any news on this? helmet as decorator would be **awesome**

**Comment by kirkbross** [comment]
Agreed! HOC.

**Comment by lucasrossini** [comment]
+1

**Comment by tmbtech** [comment]
Closing - This issues is over a year old. If needed please feel free to file a new issue.
