### ISSUE TITLE
Flash of unset title / title set to '' when undefined or null

### ISSUE THREAD

**Issue by zimok** [nfl/react-helmet#7]
There are certain cases in which props are passing an empty title before a re-render occurs (for example while waiting for async data). 

This leads to "flash of unset title" in the browser which it could be considered a strange behaviour from a user-perspective.

Other times, something can go wrong and a title is completely empty. I think it's better to keep the previous title instead of setting it to ''.

I fixed this client side by adding a simple control in `Helmet.jsx` here: https://github.com/zimok/react-helmet/blob/master/src/Helmet.jsx#L127

**Comment by cwelch5** [comment]
Excellent point.  Thanks for catching this.  Certainly if a title is not specified in a nested component, the closest parent with a defined title should be used.

If you'd like to submit a PR, we'd certainly consider it.  I took a look at your fix - it looks great, however please make sure to run the code through our linter to verify it complies with the linting standards.

Thanks.

**Comment by zimok** [comment]
Ok, give me some time to wrap up things and I definitely submit a PR.

**Comment by cwelch5** [comment]
Thank you for finding this issue.  We've fixed the issue in d6541d7e89737a9aa7d44837148b2f7651b6f6d3
