### ISSUE TITLE
Title Does Not Update on Tab Switch with Interval-based Updates

### ISSUE THREAD

**Issue by gccornejo441** [nfl/react-helmet#713]
### Environment
- Browser: Chrome 90.0.4430.212
- React version: 17.0.2
- React Helmet version: 6.1.0

### Reproduction Link
- [CodeSandbox  Wear A Helmet](https://codesandbox.io/p/sandbox/wear-a-helmet-coding-9gjzsd?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluu9d8lc0006356j2cfdcj1f%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluu9d8lb0002356jfr5ma18b%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluu9d8lb0003356jcewoffsm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluu9gsmp007y356jls0hfbjj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluu9d8lb0002356jfr5ma18b%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluu9d8la0001356jgtxm3x39%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522cluu9d8lb0002356jfr5ma18b%2522%252C%2522activeTabId%2522%253A%2522cluu9d8la0001356jgtxm3x39%2522%257D%252C%2522cluu9d8lb0003356jcewoffsm%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cluu9d8lb0003356jcewoffsm%2522%257D%252C%2522cluu9gsmp007y356jls0hfbjj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluu9gshz007t356jfzo5adoz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cluu9gsmp007y356jls0hfbjj%2522%252C%2522activeTabId%2522%253A%2522cluu9gshz007t356jfzo5adoz%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to Reproduce
1. Open the provided CodeSandbox in your browser.
2. Observe the displayed time in the browser tab.
3. Switch to another browser tab and observe.
4. Switch back to the CodeSandbox tab.

### Expected Behavior
The browser tab title should continuously update every second to reflect the current time, even when the tab is not in focus.

### Actual Behavior
The browser tab title stops updating when the tab is not in focus and only resumes updating when the tab is brought back into focus.

### Additional Information
This issue may be related to how modern browsers handle background tabs, potentially throttling JavaScript execution, which affects dynamic updates to the `<title>` element managed by React Helmet.

### Possible Solution
Investigating if React Helmet's internal handling of the `<title>` tag update could be optimized for background tabs could be a starting point.

**Comment by gccornejo441** [comment]
If you don't plan on using React-Helmet

`import { useEffect, useState } from "react";
import "./styles.css";
import { Helmet } from 'react-helmet';

export default function App() {
  const [date, setDate] = useState<Date>(new Date());

  useEffect(() => {
  setInterval(() => setDate(new Date()), 1000);
    document.title = date.toLocaleTimeString();

  }, [date]);

  return (
    <div className="App">
      <h1 style={{color: 'red'}}>The current time is {date.toLocaleTimeString()}</h1>
    </div>
  );
}
`

**Comment by schontz** [comment]
Intervals are paused and/or run much less frequently when tabs are not in focus. This is by design so that background tabs do not take a lot of resources.

**Comment by gccornejo441** [comment]
> Intervals are paused and/or run much less frequently when tabs are not in focus. This is by design so that background tabs do not take a lot of resources.

I found a solution to my particular use case.  Using a web worker.
