### ISSUE TITLE
Helmet.rewind() returns undefined.

### ISSUE THREAD

**Issue by Peege151** [nfl/react-helmet#75]
Given the following code:
```
    const componentHTML = ReactDOMServer.renderToString(<InitialComponent />);
    const head = Helmet.rewind();
    console.log('head ', head)
```

head just returns undefined.  Given that we're not actually passing anything INTO the rewind function, what would cause this function to return undefined?  I'm just trying to wrap my head around how this function is supposed to work. I tried to peek through the src but to no avail.

Using 2.2.0

**Comment by cwelch5** [comment]
Thanks for your interest in React Helmet.  In your particular case, you aren't using the Helmet component in your `renderToString` call.  If you pass props to Helmet, per the API, you will be able to use `rewind()` on the server to extract your head values for prerendering purposes.

Please refer to the README for common use cases for Helmet and let us know how it goes.  Thanks.
