### ISSUE TITLE
Helmet title update causes Chrome to reload fonts when CSS file included in link attribute

### ISSUE THREAD

**Issue by neilius** [nfl/react-helmet#76]
My `Application` component has a Helmet reference similar to the following:

```
<Helmet
    titleTemplate='%s | My Site'
    link={[
        rel:'stylesheet', type:'text/css','href':'http://<domain>/myfont.css'}
    ]}
/>
```
and the only content within the CSS file is a few font-face declaration for the various weights of the font:
```
@font-face {
    font-family: 'MyFont';
    src: url('MyFont-Regular.eot');
    src: url('MyFont-Regular.eot?#iefix') format('embedded-opentype'),
         url('MyFont-Regular.woff') format('woff');
    font-weight: 400;
    font-style: normal;
}
@font-face {
    font-family: 'MyFont';
    src: url('MyFont-Regular-Oblique.eot');
    src: url('MyFont-Regular-Oblique.eot?#iefix') format('embedded-opentype'),
         url('MyFont-Regular-Oblique.woff') format('woff');
    font-weight: 400;
    font-style: italic;
}

@font-face {
    font-family: 'MyFont';
    src: url('MyFont-Medium.eot');
    src: url('MyFont-Medium.eot?#iefix') format('embedded-opentype'),
         url('MyFont-Medium.woff') format('woff');
    font-weight: 500;
    font-style: normal;
}
```

With this set up, any time the title updates, I see a Flash of Invisible Text (FOIT) while Chrome reloads the font. This is occurring within an infinite scrolling context where the page title updates regularly and also occurs when navigating between different routes in the app. When I hardcode the `<link>` tag with the CSS file, the FOIT doesn't happen and the type doesn't flash when the page changes. I'm only seeing this issue in Chrome; I tested in Firefox and Safari and neither showed the behavior. Is my usage incorrect or is there an underlying issue with how Chrome interacts with Helmet?

**Comment by cwelch5** [comment]
Your usage looks correct.  Thanks for bringing this use case to our attention.   I can see why this may be the case, as when the props to Helmet change, all the tags are removed and repopulated.  I'm curious as well why this would be apparent in just Chrome.

This will require a bit of investigation as to why it only shows up in Chrome, but the fix here seems to be to check individual tags during client state change and only update the ones that have changed.

**Comment by lemonCMS** [comment]
I may case, i get an FOUC, but the solution would be the same i guess, i hope to see a fix soon.

**Comment by lemonCMS** [comment]
I have created an fix, perhaps take a look at the solution i created. 

https://github.com/lemonCMS/react-helmet/blob/master/src/Helmet.jsx#L132-L165

**Comment by neilius** [comment]
Awesome, thanks for the fix!
