### ISSUE TITLE
Dynamicly change title

### ISSUE THREAD

**Issue by DGizmo** [nfl/react-helmet#77]
What is the proper way to change title dynamicly on client-side?
I want to use 
```javascript 
<Helmet title={this.getTitle.bind(this)}/>
```
But console brings me warnings about proptypes.
So, I can do a PR with 
```javascript
title: _react2["default"].PropTypes.oneOfType([   _react2["default"].PropTypes.string,
_react2["default"].PropTypes.func]),
```
in Helmet.js 339 string

**Comment by Mosho1** [comment]
Since it's inside the component's render function, you can just call the function. It'll get updated as much as possible.

**Comment by cwelch5** [comment]
@DGizmo - To dynamically set the title, you can call your function earlier in the render function and save to a variable.  Or you can set a variable in your state.

I don't think we want to allow functions as props for the title.
