### ISSUE TITLE
Allow to use helmet as a parent compoment

### ISSUE THREAD

**Issue by Spy-Seth** [nfl/react-helmet#78]
It would be nice to us Helmet as a parent component like this:

```javascript
<Helmet title={this.context.intl.formatMessage({id: messageKey}>
    <div className="my-page-component">
        ...
    </div>
</Helmet>
```

It will avoid the need to add some unnecessary `div` in some case.

**Comment by cwelch5** [comment]
We recently deprecated this usage as we found having children inside the Helmet component made the componentShouldUpdate check useless.  Every time the function was called, the children object comparison always failed, thus Helmet always re-rendered and changed the DOM.
