### ISSUE TITLE
Server Meta ignored when Object key starts with 'content'

### ISSUE THREAD

**Issue by romaleev** [nfl/react-helmet#80]
Steps to reproduce:
	`let a = [{'name': 'description', 'content': 'This is the English META description'}];`
	`let b 	= [{'content': 'This is the English META description', 'name': 'description'}];`
1)	`<Helmet meta={a}/>
	Helmet.rewind().meta.toString() === '<meta data-react-helmet="true" name="description" content="This is the English META description"/>' //correct`
2)	`<Helmet meta={b}/>
	Helmet.rewind().meta.toString() === '' //incorrect`

Usually Object does not guarantee the key order, but:
	`console.log(1, a);`
	`console.log(2, b);`
Produces in browser (Chrome 47):
	`1 [ { content: 'This is the English META description', name: 'description' } ]`
	`2 [ { content: 'This is the English META description', name: 'description' } ]`
Produces in Node (0.12.7):
	`1 [ { name: 'description', content: 'This is the English META description' } ]`
	`2 [ { content: 'This is the English META description', name: 'description' } ]`

**Comment by cwelch5** [comment]
Thank you, yes, this a bug.  At the moment, the order of attributes does matter when building tags.  The first recognized valid attribute is used to categorize and identify that tag.  The solution at a minimum should search all attributes and determine the best one to identify that tag.  The API may be better served allowing a separate attribute as the "primary", with the additional attributes in an array.  I'll need to give this some thought.

**Comment by ChrisCinelli** [comment]
You want at least to prioritize `name` and `property` if they are present

**Comment by romaleev** [comment]
Solution which works both in browsers and Node.js: 
`let meta = meta && meta.map((item)=>{
	let {name, property} = item;
	if(name) return Object.assign({name}, item);
	if(property) return Object.assign({property}, item);
	return item;
}) || [];`
