### ISSUE TITLE
server rendering returns <noscript></noscript> where <Helmet /> is implemented

### ISSUE THREAD

**Issue by SkateFreak** [nfl/react-helmet#81]
my React Component:

    render() {
        return (
            <div id="home">
                <Helmet title="Home" />
                <h2>test dict</h2>
            </div>
        )
    }

my rendred markup (using renderToStaticMarkup):

    <div id="app">
        <div id="home">
            <noscript></noscript>
            <h2>Home</h2>
        </div>
    </div>

is there any way around this issue?
thanks.

**Comment by cwelch5** [comment]
Are you saying `renderToString` gives you a different result?  Is this on the server or the client?  If on the server, make sure to follow the README on how to render as a string or as React components.
