### ISSUE TITLE
Feature request: .toDocument() which sets document.head.title etc

### ISSUE THREAD

**Issue by dbkaplun** [nfl/react-helmet#85]
(I'd love to use `.toComponent()`, is there an example that shows how to use it? I see [react-helmet-example](https://github.com/mattdennewitz/react-helmet-example) but it is server-side.)

**Comment by cwelch5** [comment]
There's an example component in the README.  This is completely up to how users want to write their Node server.  `react-helmet-example` uses `renderToString()` and writes the string straight to the response.  We use a similar process in-house.  I believe the users who use `.toComponent()` option want to render the Helmet properties to components to use in another component that actually renders the whole HTML page on the server.  Here's the issue that started the conversation to get the feature put into Helmet - #25

**Comment by dbkaplun** [comment]
@cwelch5 thank you. Does that mean that I cannot use react-helmet client-side?

**Comment by cwelch5** [comment]
No, Helmet completely supports a universal/isomorphic application.  `react-helmet-example` shows a good example of how to render Helmet on the client and server.  It still needs to be updated, but with the new API, using `react-helmet-example`, you would use the `.toString()` function on the server.

Have you tried to render on the client to start?  What are your results?  I would use some sort of react starter kit just to see how Helmet can work for you, if you don't already have an app running.
