### ISSUE TITLE
Helmet.rewind() returning undefined 

### ISSUE THREAD

**Issue by abhijeetNmishra** [nfl/react-helmet#88]
```
const head = Helmet.rewind();
```
I am getting undefined for above code on server side ?

**Comment by cwelch5** [comment]
Before you call `rewind`, are you rendering a Helmet component with valid parameters?  And are there any warnings or errors otherwise?  Please refer to the README for various examples to get you started.

**Comment by sergesemashko** [comment]
I can reproduce the same issue when there is no `<Helmet />` render occurred in components on server rendering. 
Returning a fallback for mapped state on `rewind()` call would help to avoid the error. If `rewind()` is wrapped by following code, `rewind()` doesn't return undefined anymore:
```js
static rewind = () => {
            let mappedState = Component.rewind();
            if (!mappedState) {
                // provide fallback if mappedState is undefined
                mappedState = mapStateOnServer({
                    title: "",
                    baseTag: "",
                    metaTags: "",
                    linkTags: "",
                    scriptTags: ""
                });
            }

            return mappedState;
        }
```

**Comment by cwelch5** [comment]
@sergesemashko Thx for the PR, although shouldn't users check for undefined when they get a result back from Helmet.rewind()?  When a Helmet is not rendered on a particular route, then the expected behavior would be to get undefined for the state because there is no Helmet state on the server.  If you need defaults, you can provide them in the server on your own with something like this:

```
const head = {
	title: "",
	base: "",
	meta: "",
	link: "",
	script: "",
	...Helmet.rewind()
};
```

**Comment by cwelch5** [comment]
@sergesemashko Thx for the PR, will take a look soon.

**Comment by sergesemashko** [comment]
@cwelch5, no problem. Myself and at least one more dev from referenced project run into this issue. Adding a check to every project that might run into the same issue seems a big code duplication to me :) I would suggest to prevent it from the package itself, or at least warn users about the check by docs or examples in case of empty state.

**Comment by maketroli** [comment]
You have the same issue I had.

Probably you removed HtmlHeaderTags from the folder `app/Documents`

that component is

```
// LIBRARY
import React from 'react';
import Helmet from 'react-helmet';

// TODO: do it in store maybe
const metas = require('../../../assets/config.json').helmet;

const HtmlHeaderTags = () => (
  <div>
    <Helmet link={metas.link} meta={metas.meta} title={metas.title} />
  </div>
);

HtmlHeaderTags.prototype.displayName = 'HtmlHeaderTags';

export default HtmlHeaderTags;
```

then you have to included in /components/App/App.js

```
// LIBRARY
import React from 'react';

// COMPONENT
import Header from '../Header/Header';
import Footer from '../Footer/Footer';
// import Recorder from '../Recorder/Recorder';
import HtmlHeaderTags from '../Document/HtmlHeaderTags'; // HERE

const { PropTypes } = React;

// css
if (process.env.BROWSER) {
  require('./_App.scss');
  require('./_App.sass');
  require('bootstrap/dist/css/bootstrap.css');
  require('file?name=favicon.ico!../../images/favicon.ico');
}

export default class App extends React.Component {
  constructor() {
    super();
  }

  render() {
    return (
      <div>
        <HtmlHeaderTags /> //HERE
        <Header />
        <div className='main-content'>
          {this.props.children}
        </div>
        <Footer />
      </div>
    );
  }
}

App.propTypes = {
  children: PropTypes.node
};

App.prototype.displayName = 'App';
```
